import { createContext, useContext, useState, ReactNode } from "react";

export type Language = "en" | "es" | "de" | "fr" | "pt" | "ja" | "ar";

const translations = {
  en: {
    // Navigation
    nav_home: "Home",
    nav_products: "Products",
    nav_all_products: "All Products",
    nav_skincare: "Skincare",
    nav_skincare_desc: "Skin care products",
    nav_makeup: "Makeup",
    nav_makeup_desc: "Color cosmetics",
    nav_haircare: "Hair Care",
    nav_haircare_desc: "Hair management",
    nav_fragrance: "Fragrance",
    nav_fragrance_desc: "Signature perfumes",
    nav_bodycare: "Body Care",
    nav_bodycare_desc: "Body care products",
    nav_health: "Health Foods",
    nav_health_desc: "Health supplements",
    nav_tools: "Beauty Tools",
    nav_tools_desc: "Beauty accessories",
    nav_brand_story: "Brand Story",
    nav_qa: "Q&A",
    nav_ranking: "Ranking",
    nav_sale: "Sale",
    nav_routine: "Make Your Routine",
    nav_contact: "Contact",
    nav_admin: "Admin",
    nav_menu: "Menu",
    nav_mypage: "My Page",
    nav_login: "Sign In",

    // Hero
    hero_tagline: "Premium Korean Beauty",
    hero_title: "Bloom & Grace",
    hero_subtitle: "Infused with Korean beauty wisdom. Crafted with nature's finest ingredients to complete your elegance.",
    hero_shop: "Shop Collection",
    hero_story: "Our Story",

    // Featured Products
    featured_tagline: "HOT PRODUCT",
    featured_title: "Featured Products",
    featured_subtitle: "Beauty essentials embracing Korean cosmetic",
    featured_view_all: "View All Products",

    // About
    about_tagline: "Our Philosophy",
    about_title: "Our Story",
    about_p1: "Welcome to Bloom & Grace, where Korean beauty wisdom meets autumn's gentle embrace. Like walking through a serene garden kissed by fall's golden light, where soft pink petals rest on verdant grass, our boutique is a sanctuary of refined elegance.",
    about_p2: "Every product in our collection embodies the meticulous care of Korean beauty traditions—infused with natural botanicals, autumn herbs, and the gentle touch of nature's finest ingredients. We believe beauty should feel as luxurious and comforting as the warm glow of an autumn afternoon, where every detail whispers sophistication.",
    about_p3: "From our signature formulations to our thoughtfully designed packaging, each element is crafted to enhance your natural radiance while nourishing your skin with the purity of nature. Join us in celebrating beauty that blooms gracefully from within, just like the changing seasons.",
    about_since: "Crafted with care since 2024",

    // Footer
    footer_desc: "A brand embracing Korean beauty wisdom. Crafted with nature's finest ingredients to complete your elegance.",
    footer_products: "Products",
    footer_new: "New Arrivals",
    footer_bestseller: "Bestsellers",
    footer_brand: "Brand",
    footer_store: "Store Info",
    footer_sustainability: "Sustainability",
    footer_ingredients: "Ingredients Story",
    footer_careers: "Careers",
    footer_support: "Support",
    footer_faq: "FAQ",
    footer_shipping: "Shipping Info",
    footer_returns: "Returns & Exchanges",
    footer_terms: "Terms of Service",
    footer_rights: "All rights reserved.",
    footer_cs: "Customer Service: 1588-1234 | Email: contact@bloomandgrace.com",

    // Products page
    products_title: "All Products",
    products_subtitle: "Premium Korean cosmetics collection",
    products_search: "Search products...",
    products_search_btn: "Search",
    products_all: "All",
    products_category: "Category",
    products_popular: "Popular",
    products_newest: "Newest",
    products_price_low: "Price: Low to High",
    products_price_high: "Price: High to Low",
    products_rating: "Top Rated",
    products_all_prices: "All Prices",
    products_under_20k: "Under $20",
    products_20k_50k: "$20 - $50",
    products_over_50k: "Over $50",
    products_no_results: "No products found.",

    // Product Detail
    pd_reviews: "reviews",
    pd_stock: "In Stock",
    pd_out_of_stock: "Out of Stock",
    pd_add_to_cart: "Add to Cart",
    pd_review_section: "Reviews",
    pd_all: "All",
    pd_above: "& above",
    pd_write_review: "Write a Review",
    pd_review_title: "Title",
    pd_review_content: "Write your review...",
    pd_submit_review: "Submit Review",
    pd_no_reviews: "No reviews yet.",
    pd_anonymous: "Anonymous",
    pd_loading: "Loading...",
    pd_not_found: "Product not found.",
    pd_already_reviewed: "You've already reviewed this product.",
    pd_review_fail: "Failed to submit review.",
    pd_review_success: "Review submitted successfully!",

    // Cart
    cart_title: "Shopping Cart",
    cart_empty: "Your cart is empty",
    cart_total: "Total",
    cart_checkout: "Checkout",
    cart_added: "Added to cart!",
    cart_login_required: "Please sign in first.",

    // Product Card
    pc_add_to_cart: "Add to Cart",

    // Auth
    auth_title: "Bloom & Grace",
    auth_subtitle: "Premium Korean Cosmetics",
    auth_login: "Sign In",
    auth_signup: "Join Us",
    auth_email: "Email",
    auth_email_placeholder: "Enter your email",
    auth_password: "Password",
    auth_password_placeholder: "Enter your password",
    auth_name: "Name",
    auth_name_placeholder: "Enter your name",
    auth_phone: "Phone",
    auth_phone_placeholder: "Enter your phone number",
    auth_confirm_password: "Confirm Password",
    auth_confirm_password_placeholder: "Re-enter your password",
    auth_logging_in: "Signing in...",
    auth_signing_up: "Signing up...",
    auth_login_success: "Signed in successfully!",
    auth_login_fail: "Failed to sign in.",
    auth_signup_success: "Account created! Please complete your profile.",
    auth_signup_fail: "Failed to create account.",
    auth_google_signin: "Sign in with Google",
    auth_google_signup: "Sign up with Google",
    auth_or: "or",
    auth_password_mismatch: "Passwords do not match.",
    auth_agree_required: "Please agree to the terms.",
    auth_terms_agree: "I agree to the Terms of Service and Privacy Policy.",
    auth_benefits_title: "Member Benefits",
    auth_benefit_1: "10% welcome coupon on sign-up",
    auth_benefit_2: "3% reward points on every purchase",
    auth_benefit_3: "Birthday month special gifts & coupons",
    // Profile Completion
    cp_title: "Complete Your Profile",
    cp_subtitle: "Please fill in your shipping details to start shopping.",
    cp_country: "Country",
    cp_country_code: "Country Code",
    cp_address: "Address",
    cp_detail_address: "Detail Address",
    cp_shipping_address: "Shipping Address",
    cp_customs_number: "Customs Number (PCCC)",
    cp_customs_hint: "Required for international shipping",
    cp_postal: "Postal Code",
    cp_city: "City / State",
    cp_phone: "Phone Number",
    cp_save: "Save & Continue",
    cp_saving: "Saving...",
    cp_skip: "Skip for now",
    cp_success: "Profile saved successfully!",
    cp_fail: "Failed to save profile.",

    // Checkout
    co_title: "Checkout",
    co_shipping: "Shipping Address",
    co_recipient: "Recipient",
    co_phone: "Phone",
    co_address: "Address",
    co_detail_address: "Detail Address",
    co_postal: "Postal Code",
    co_city: "City",
    co_payment: "Payment Method",
    co_card: "Credit Card",
    co_bank: "Bank Transfer",
    co_kakao: "KakaoPay",
    co_naver: "NaverPay",
    co_summary: "Order Summary",
    co_coupon: "Coupon Code",
    co_apply: "Apply",
    co_discount: "Discount",
    co_total: "Total",
    co_processing: "Processing...",
    co_pay: "Pay",
    co_login_required: "Please sign in first.",
    co_cart_empty: "Your cart is empty.",
    co_invalid_coupon: "Invalid coupon.",
    co_min_order: "Minimum order amount is",
    co_coupon_applied: "Coupon applied!",
    co_discount_amount: "discount",
    co_order_success: "Order placed successfully!",
    co_order_fail: "Failed to place order.",

    // MyPage
    mp_title: "My Page",
    mp_logout: "Sign Out",
    mp_orders: "Orders",
    mp_wishlist: "Wishlist",
    mp_profile: "Profile",
    mp_no_orders: "No orders yet.",
    mp_order_date: "Order",
    mp_subtotal: "Subtotal",
    mp_no_wishlist: "No items in wishlist.",
    mp_email: "Email",
    mp_name: "Name",
    mp_phone: "Phone",
    mp_login_required: "Please sign in first.",

    // Order statuses
    status_pending: "Pending",
    status_confirmed: "Confirmed",
    status_shipping: "Shipping",
    status_delivered: "Delivered",
    status_cancelled: "Cancelled",

    // Contact
    contact_tagline: "Get in Touch",
    contact_title: "Contact Us",
    contact_subtitle: "Have questions or need help? We're here for you.",
    contact_send: "Send a Message",
    contact_name: "Name",
    contact_email: "Email",
    contact_phone: "Phone",
    contact_message: "Message",
    contact_message_placeholder: "Tell us what's on your mind...",
    contact_submit: "Send Message",
    contact_info: "Contact Information",
    contact_address_title: "Headquarters",
    contact_address_value: "123 Teheranro, Gangnam-gu\nSeoul, South Korea",
    contact_phone_title: "Phone",
    contact_phone_value: "Main: +82-2-1234-5678\nSupport: 1588-1234",
    contact_email_title: "Email",
    contact_email_value: "General: contact@bloomandgrace.com\nPartners: partnership@bloomandgrace.com",
    contact_hours_title: "Business Hours",
    contact_hours_value: "Weekdays: 10:00 AM - 6:00 PM\nLunch: 12:00 PM - 1:00 PM\nWeekends & Holidays: Closed",
    contact_visit: "Book a Visit",
    contact_visit_desc: "Reserve ahead for a more convenient consultation experience.",
    contact_reserve: "Reserve",
    contact_map: "Directions",
    contact_map_desc: "Map area (Google Maps or Kakao Map integration)",

    // QA
    qa_tagline: "Frequently Asked Questions",
    qa_title: "Q&A",
    qa_subtitle: "We've gathered the most commonly asked questions. Feel free to contact us for anything else.",
    qa_not_found: "Couldn't find your answer?",
    qa_not_found_desc: "Contact our support team and we'll be happy to help.",
    qa_email_btn: "Email Us",
    qa_phone_btn: "Call Us",
    // QA Categories
    qa_cat_product: "Products",
    qa_cat_shipping: "Shipping & Orders",
    qa_cat_returns: "Returns & Exchanges",
    qa_cat_membership: "Membership & Benefits",
    qa_cat_sustainability: "Sustainability",
    qa_cat_support: "Customer Support",
    // QA Questions
    qa_q1: "What ingredients are your products made of?",
    qa_a1: "Our products are made with premium Korean natural ingredients including green tea extract, rose essence, yuzu extract, and pearl powder. We never use parabens, artificial fragrances, or animal-derived ingredients.",
    qa_q2: "How do I choose products for my skin type?",
    qa_a2: "Each product page displays the recommended skin type. We offer gentle lines for sensitive skin, intensive moisture lines for dry skin, and sebum care lines for oily skin. Please don't hesitate to contact us.",
    qa_q3: "Do you test on animals?",
    qa_a3: "Absolutely not. Bloom & Grace is committed to being cruelty-free, and all our products are certified. We pursue ethical and sustainable beauty.",
    qa_q4: "How long does shipping take?",
    qa_a4: "Domestic shipping arrives within 2-3 business days. International shipping takes 5-10 business days. Remote areas may require 1-2 additional days. Tracking numbers are sent via text and email.",
    qa_q5: "What are the shipping costs?",
    qa_a5: "Free domestic shipping on orders over $50. Orders under $50 have a $3 shipping fee. International shipping varies by country and is calculated at checkout.",
    qa_q6: "Can I cancel or modify my order?",
    qa_a6: "Orders can be cancelled or modified through customer service until the 'preparing shipment' stage. After shipping begins, you'll need to use the returns/exchange process.",
    qa_q7: "How do I return or exchange a product?",
    qa_a7: "Returns and exchanges are available within 7 days of receipt for unopened products. Contact customer service for return address and procedures. Return shipping for change of mind is the customer's responsibility.",
    qa_q8: "I received a defective product.",
    qa_a8: "We offer full refunds or exchanges for defective products. Please contact customer service with photos, and we'll handle it promptly. We cover the return shipping cost.",
    qa_q9: "Are there sign-up benefits?",
    qa_a9: "New members receive a 10% discount coupon, and 3% of purchases are accumulated as points. Special coupons and gifts are provided during your birthday month.",
    qa_q10: "How do I use reward points?",
    qa_a10: "Points can be used starting from $1 and work like cash for product purchases. Points are valid for 2 years from the date earned.",
    qa_q11: "Do you use eco-friendly packaging?",
    qa_a11: "Yes, all products are packaged with recyclable materials and we minimize unnecessary plastic use. We use FSC-certified paper and biodegradable materials.",
    qa_q12: "Do you offer refill products?",
    qa_a12: "Main skincare lines offer refill products at 20% less than regular prices. You can return empty containers to our store for reward points.",
    qa_q13: "What are customer service hours?",
    qa_a13: "We operate weekdays from 10 AM to 6 PM, with a lunch break from 12 PM to 1 PM. Weekends and holidays are closed. Email inquiries are accepted 24/7.",
    qa_q14: "Is 1:1 consultation available?",
    qa_a14: "Yes, you can get personalized consultation via our website chat or email (contact@bloomandgrace.com). Feel free to ask about skin concerns, product recommendations, and more.",

    // Currency
    currency: "$",
    currency_suffix: "",
  },
  es: {
    nav_home: "Inicio",
    nav_products: "Productos",
    nav_all_products: "Todos los Productos",
    nav_skincare: "Cuidado de Piel",
    nav_skincare_desc: "Productos para el cuidado de la piel",
    nav_makeup: "Maquillaje",
    nav_makeup_desc: "Cosméticos de color",
    nav_haircare: "Cuidado Capilar",
    nav_haircare_desc: "Gestión del cabello",
    nav_fragrance: "Fragancias",
    nav_fragrance_desc: "Perfumes exclusivos",
    nav_bodycare: "Cuidado Corporal",
    nav_bodycare_desc: "Productos corporales",
    nav_health: "Suplementos",
    nav_health_desc: "Suplementos alimenticios",
    nav_tools: "Herramientas",
    nav_tools_desc: "Accesorios de belleza",
    nav_brand_story: "Nuestra Historia",
    nav_qa: "Preguntas",
    nav_ranking: "Ranking",
    nav_sale: "Ofertas",
    nav_routine: "Crea Tu Rutina",
    nav_contact: "Contacto",
    nav_admin: "Admin",
    nav_menu: "Menú",
    nav_mypage: "Mi Página",
    nav_login: "Iniciar Sesión",

    hero_tagline: "Belleza Coreana Premium",
    hero_title: "Bloom & Grace",
    hero_subtitle: "Cosméticos premium con la sabiduría de la belleza coreana. Elaborados con los mejores ingredientes naturales para completar tu elegancia.",
    hero_shop: "Ver Colección",
    hero_story: "Nuestra Historia",

    featured_tagline: "HOT PRODUCT",
    featured_title: "Productos Destacados",
    featured_subtitle: "Esenciales de belleza que abrazan la cosmética coreana",
    featured_view_all: "Ver Todos",

    about_tagline: "Nuestra Filosofía",
    about_title: "Nuestra Historia",
    about_p1: "Bienvenidos a Bloom & Grace, donde la sabiduría de la belleza coreana se encuentra con el suave abrazo del otoño. Como caminar por un jardín sereno besado por la luz dorada del otoño, nuestra boutique es un santuario de elegancia refinada.",
    about_p2: "Cada producto encarna el cuidado meticuloso de las tradiciones de belleza coreana—infundido con botánicos naturales, hierbas otoñales y el toque suave de los mejores ingredientes de la naturaleza.",
    about_p3: "Desde nuestras formulaciones exclusivas hasta nuestro empaque cuidadosamente diseñado, cada elemento está elaborado para realzar tu resplandor natural mientras nutre tu piel con la pureza de la naturaleza.",
    about_since: "Elaborado con cuidado desde 2024",

    footer_desc: "Marca de cosméticos premium que abraza la sabiduría de la belleza coreana.",
    footer_products: "Productos",
    footer_new: "Novedades",
    footer_bestseller: "Más Vendidos",
    footer_brand: "Marca",
    footer_store: "Tiendas",
    footer_sustainability: "Sostenibilidad",
    footer_ingredients: "Ingredientes",
    footer_careers: "Empleo",
    footer_support: "Soporte",
    footer_faq: "Preguntas Frecuentes",
    footer_shipping: "Envíos",
    footer_returns: "Devoluciones",
    footer_terms: "Términos",
    footer_rights: "Todos los derechos reservados.",
    footer_cs: "Atención al cliente: 1588-1234 | Email: contact@bloomandgrace.com",

    products_title: "Todos los Productos",
    products_subtitle: "Colección premium de cosméticos coreanos",
    products_search: "Buscar productos...",
    products_search_btn: "Buscar",
    products_all: "Todos",
    products_category: "Categoría",
    products_popular: "Popular",
    products_newest: "Más Reciente",
    products_price_low: "Menor Precio",
    products_price_high: "Mayor Precio",
    products_rating: "Mejor Valorado",
    products_all_prices: "Todos los Precios",
    products_under_20k: "Menos de $20",
    products_20k_50k: "$20 - $50",
    products_over_50k: "Más de $50",
    products_no_results: "No se encontraron productos.",

    pd_reviews: "reseñas",
    pd_stock: "En Stock",
    pd_out_of_stock: "Agotado",
    pd_add_to_cart: "Agregar al Carrito",
    pd_review_section: "Reseñas",
    pd_all: "Todas",
    pd_above: "y más",
    pd_write_review: "Escribir Reseña",
    pd_review_title: "Título",
    pd_review_content: "Escribe tu reseña...",
    pd_submit_review: "Enviar Reseña",
    pd_no_reviews: "Aún no hay reseñas.",
    pd_anonymous: "Anónimo",
    pd_loading: "Cargando...",
    pd_not_found: "Producto no encontrado.",
    pd_already_reviewed: "Ya has dejado una reseña.",
    pd_review_fail: "Error al enviar reseña.",
    pd_review_success: "¡Reseña enviada!",

    cart_title: "Carrito",
    cart_empty: "Tu carrito está vacío",
    cart_total: "Total",
    cart_checkout: "Pagar",
    cart_added: "¡Agregado al carrito!",
    cart_login_required: "Inicia sesión primero.",

    pc_add_to_cart: "Al Carrito",

    auth_title: "Bloom & Grace",
    auth_subtitle: "Cosméticos Coreanos Premium",
    auth_login: "Iniciar Sesión",
    auth_signup: "Únete",
    auth_email: "Correo",
    auth_email_placeholder: "Tu correo electrónico",
    auth_password: "Contraseña",
    auth_password_placeholder: "Tu contraseña",
    auth_name: "Nombre",
    auth_name_placeholder: "Tu nombre",
    auth_phone: "Teléfono",
    auth_phone_placeholder: "Tu número de teléfono",
    auth_confirm_password: "Confirmar Contraseña",
    auth_confirm_password_placeholder: "Repite tu contraseña",
    auth_logging_in: "Iniciando...",
    auth_signing_up: "Registrando...",
    auth_login_success: "¡Sesión iniciada!",
    auth_login_fail: "Error al iniciar sesión.",
    auth_signup_success: "¡Cuenta creada! Completa tu perfil.",
    auth_signup_fail: "Error al crear cuenta.",
    auth_google_signin: "Iniciar sesión con Google",
    auth_google_signup: "Registrarse con Google",
    auth_or: "o",
    auth_password_mismatch: "Las contraseñas no coinciden.",
    auth_agree_required: "Acepta los términos.",
    auth_terms_agree: "Acepto los Términos de Servicio y la Política de Privacidad.",
    auth_benefits_title: "Beneficios de Membresía",
    auth_benefit_1: "Cupón de bienvenida del 10%",
    auth_benefit_2: "3% de puntos en cada compra",
    auth_benefit_3: "Regalos especiales en tu cumpleaños",
    cp_title: "Completa tu Perfil",
    cp_subtitle: "Ingresa tus datos de envío para comenzar a comprar.",
    cp_country: "País",
    cp_country_code: "Código de País",
    cp_address: "Dirección",
    cp_detail_address: "Detalle de Dirección",
    cp_shipping_address: "Dirección de Envío",
    cp_customs_number: "Número de Aduanas",
    cp_customs_hint: "Requerido para envíos internacionales",
    cp_postal: "Código Postal",
    cp_city: "Ciudad / Estado",
    cp_phone: "Teléfono",
    cp_save: "Guardar y Continuar",
    cp_saving: "Guardando...",
    cp_skip: "Omitir por ahora",
    cp_success: "¡Perfil guardado!",
    cp_fail: "Error al guardar perfil.",

    co_title: "Pagar",
    co_shipping: "Dirección de Envío",
    co_recipient: "Destinatario",
    co_phone: "Teléfono",
    co_address: "Dirección",
    co_detail_address: "Detalle",
    co_postal: "Código Postal",
    co_city: "Ciudad",
    co_payment: "Método de Pago",
    co_card: "Tarjeta de Crédito",
    co_bank: "Transferencia",
    co_kakao: "KakaoPay",
    co_naver: "NaverPay",
    co_summary: "Resumen del Pedido",
    co_coupon: "Código de Cupón",
    co_apply: "Aplicar",
    co_discount: "Descuento",
    co_total: "Total",
    co_processing: "Procesando...",
    co_pay: "Pagar",
    co_login_required: "Inicia sesión primero.",
    co_cart_empty: "Tu carrito está vacío.",
    co_invalid_coupon: "Cupón inválido.",
    co_min_order: "Monto mínimo de pedido es",
    co_coupon_applied: "¡Cupón aplicado!",
    co_discount_amount: "descuento",
    co_order_success: "¡Pedido realizado!",
    co_order_fail: "Error al realizar pedido.",

    mp_title: "Mi Página",
    mp_logout: "Cerrar Sesión",
    mp_orders: "Pedidos",
    mp_wishlist: "Favoritos",
    mp_profile: "Perfil",
    mp_no_orders: "Sin pedidos aún.",
    mp_order_date: "Pedido",
    mp_subtotal: "Subtotal",
    mp_no_wishlist: "Sin favoritos.",
    mp_email: "Correo",
    mp_name: "Nombre",
    mp_phone: "Teléfono",
    mp_login_required: "Inicia sesión primero.",

    status_pending: "Pendiente",
    status_confirmed: "Confirmado",
    status_shipping: "En Envío",
    status_delivered: "Entregado",
    status_cancelled: "Cancelado",

    contact_tagline: "Contáctanos",
    contact_title: "Contacto",
    contact_subtitle: "¿Tienes preguntas? Estamos aquí para ayudarte.",
    contact_send: "Enviar Mensaje",
    contact_name: "Nombre",
    contact_email: "Correo",
    contact_phone: "Teléfono",
    contact_message: "Mensaje",
    contact_message_placeholder: "Cuéntanos qué necesitas...",
    contact_submit: "Enviar",
    contact_info: "Información de Contacto",
    contact_address_title: "Sede Central",
    contact_address_value: "123 Teheranro, Gangnam-gu\nSeúl, Corea del Sur",
    contact_phone_title: "Teléfono",
    contact_phone_value: "Principal: +82-2-1234-5678\nSoporte: 1588-1234",
    contact_email_title: "Correo",
    contact_email_value: "General: contact@bloomandgrace.com\nSocios: partnership@bloomandgrace.com",
    contact_hours_title: "Horario",
    contact_hours_value: "Lunes a Viernes: 10:00 - 18:00\nAlmuerzo: 12:00 - 13:00\nFines de semana: Cerrado",
    contact_visit: "Reservar Visita",
    contact_visit_desc: "Reserve con anticipación para una consulta más conveniente.",
    contact_reserve: "Reservar",
    contact_map: "Cómo Llegar",
    contact_map_desc: "Área del mapa",

    qa_tagline: "Preguntas Frecuentes",
    qa_title: "Preguntas y Respuestas",
    qa_subtitle: "Hemos reunido las preguntas más frecuentes. No dudes en contactarnos.",
    qa_not_found: "¿No encontraste tu respuesta?",
    qa_not_found_desc: "Contáctanos y te ayudaremos con gusto.",
    qa_email_btn: "Enviar Correo",
    qa_phone_btn: "Llamar",
    qa_cat_product: "Productos",
    qa_cat_shipping: "Envíos y Pedidos",
    qa_cat_returns: "Devoluciones",
    qa_cat_membership: "Membresía",
    qa_cat_sustainability: "Sostenibilidad",
    qa_cat_support: "Soporte",
    qa_q1: "¿De qué ingredientes están hechos sus productos?",
    qa_a1: "Nuestros productos están hechos con ingredientes naturales premium coreanos.",
    qa_q2: "¿Cómo elijo productos para mi tipo de piel?",
    qa_a2: "Cada página de producto muestra el tipo de piel recomendado.",
    qa_q3: "¿Hacen pruebas en animales?",
    qa_a3: "Absolutamente no. Bloom & Grace es cruelty-free.",
    qa_q4: "¿Cuánto tarda el envío?",
    qa_a4: "El envío doméstico llega en 2-3 días hábiles.",
    qa_q5: "¿Cuáles son los costos de envío?",
    qa_a5: "Envío gratis en pedidos mayores a $50.",
    qa_q6: "¿Puedo cancelar o modificar mi pedido?",
    qa_a6: "Sí, hasta la etapa de preparación del envío.",
    qa_q7: "¿Cómo devuelvo un producto?",
    qa_a7: "Devoluciones disponibles dentro de 7 días para productos sin abrir.",
    qa_q8: "Recibí un producto defectuoso.",
    qa_a8: "Ofrecemos reembolso o cambio completo para productos defectuosos.",
    qa_q9: "¿Hay beneficios por registrarse?",
    qa_a9: "Nuevos miembros reciben cupón de 10% de descuento.",
    qa_q10: "¿Cómo uso los puntos de recompensa?",
    qa_a10: "Los puntos se pueden usar desde $1 como efectivo.",
    qa_q11: "¿Usan empaque ecológico?",
    qa_a11: "Sí, todos los productos usan materiales reciclables.",
    qa_q12: "¿Ofrecen recargas?",
    qa_a12: "Sí, las líneas principales ofrecen recargas con 20% de descuento.",
    qa_q13: "¿Cuál es el horario de atención?",
    qa_a13: "Lunes a viernes de 10 AM a 6 PM.",
    qa_q14: "¿Hay consulta personalizada?",
    qa_a14: "Sí, por chat o email a contact@bloomandgrace.com.",

    currency: "$",
    currency_suffix: "",
  },
  de: {
    nav_home: "Startseite",
    nav_products: "Produkte",
    nav_all_products: "Alle Produkte",
    nav_skincare: "Hautpflege",
    nav_skincare_desc: "Hautpflegeprodukte",
    nav_makeup: "Make-up",
    nav_makeup_desc: "Farbkosmetik",
    nav_haircare: "Haarpflege",
    nav_haircare_desc: "Haarpflege",
    nav_fragrance: "Düfte",
    nav_fragrance_desc: "Exklusive Parfums",
    nav_bodycare: "Körperpflege",
    nav_bodycare_desc: "Körperpflegeprodukte",
    nav_health: "Nahrungsergänzung",
    nav_health_desc: "Nahrungsergänzungsmittel",
    nav_tools: "Beauty-Tools",
    nav_tools_desc: "Beauty-Zubehör",
    nav_brand_story: "Unsere Geschichte",
    nav_qa: "FAQ",
    nav_ranking: "Ranking",
    nav_sale: "Sale",
    nav_routine: "Deine Routine",
    nav_contact: "Kontakt",
    nav_admin: "Admin",
    nav_menu: "Menü",
    nav_mypage: "Mein Konto",
    nav_login: "Anmelden",

    hero_tagline: "Premium Koreanische Schönheit",
    hero_title: "Bloom & Grace",
    hero_subtitle: "Premium-Kosmetik mit der Weisheit koreanischer Schönheit. Mit den besten natürlichen Zutaten für Ihre Eleganz.",
    hero_shop: "Kollektion ansehen",
    hero_story: "Unsere Geschichte",

    featured_tagline: "HOT PRODUCT",
    featured_title: "Empfohlene Produkte",
    featured_subtitle: "Beauty-Essentials mit koreanischer Kosmetik",
    featured_view_all: "Alle Produkte",

    about_tagline: "Unsere Philosophie",
    about_title: "Unsere Geschichte",
    about_p1: "Willkommen bei Bloom & Grace, wo koreanische Schönheitsweisheit auf die sanfte Umarmung des Herbstes trifft. Unsere Boutique ist ein Refugium raffinierter Eleganz.",
    about_p2: "Jedes Produkt verkörpert die sorgfältige Pflege koreanischer Schönheitstraditionen—durchdrungen von natürlichen Pflanzenextrakten und den besten Zutaten der Natur.",
    about_p3: "Von unseren exklusiven Formulierungen bis zu unserem durchdacht gestalteten Verpackungsdesign ist jedes Element darauf ausgerichtet, Ihre natürliche Ausstrahlung zu verstärken.",
    about_since: "Mit Sorgfalt gefertigt seit 2024",

    footer_desc: "Premium-Kosmetikmarke mit koreanischer Schönheitsweisheit.",
    footer_products: "Produkte",
    footer_new: "Neuheiten",
    footer_bestseller: "Bestseller",
    footer_brand: "Marke",
    footer_store: "Filialen",
    footer_sustainability: "Nachhaltigkeit",
    footer_ingredients: "Inhaltsstoffe",
    footer_careers: "Karriere",
    footer_support: "Support",
    footer_faq: "Häufige Fragen",
    footer_shipping: "Versand",
    footer_returns: "Rückgabe",
    footer_terms: "AGB",
    footer_rights: "Alle Rechte vorbehalten.",
    footer_cs: "Kundenservice: 1588-1234 | E-Mail: contact@bloomandgrace.com",

    products_title: "Alle Produkte",
    products_subtitle: "Premium koreanische Kosmetik-Kollektion",
    products_search: "Produkte suchen...",
    products_search_btn: "Suchen",
    products_all: "Alle",
    products_category: "Kategorie",
    products_popular: "Beliebt",
    products_newest: "Neueste",
    products_price_low: "Preis aufsteigend",
    products_price_high: "Preis absteigend",
    products_rating: "Bestbewertet",
    products_all_prices: "Alle Preise",
    products_under_20k: "Unter 20€",
    products_20k_50k: "20€ - 50€",
    products_over_50k: "Über 50€",
    products_no_results: "Keine Produkte gefunden.",

    pd_reviews: "Bewertungen",
    pd_stock: "Auf Lager",
    pd_out_of_stock: "Ausverkauft",
    pd_add_to_cart: "In den Warenkorb",
    pd_review_section: "Bewertungen",
    pd_all: "Alle",
    pd_above: "und mehr",
    pd_write_review: "Bewertung schreiben",
    pd_review_title: "Titel",
    pd_review_content: "Schreiben Sie Ihre Bewertung...",
    pd_submit_review: "Absenden",
    pd_no_reviews: "Noch keine Bewertungen.",
    pd_anonymous: "Anonym",
    pd_loading: "Laden...",
    pd_not_found: "Produkt nicht gefunden.",
    pd_already_reviewed: "Sie haben bereits bewertet.",
    pd_review_fail: "Bewertung fehlgeschlagen.",
    pd_review_success: "Bewertung eingereicht!",

    cart_title: "Warenkorb",
    cart_empty: "Ihr Warenkorb ist leer",
    cart_total: "Gesamt",
    cart_checkout: "Zur Kasse",
    cart_added: "Zum Warenkorb hinzugefügt!",
    cart_login_required: "Bitte melden Sie sich an.",

    pc_add_to_cart: "In den Korb",

    auth_title: "Bloom & Grace",
    auth_subtitle: "Premium Koreanische Kosmetik",
    auth_login: "Anmelden",
    auth_signup: "Mitglied werden",
    auth_email: "E-Mail",
    auth_email_placeholder: "Ihre E-Mail",
    auth_password: "Passwort",
    auth_password_placeholder: "Ihr Passwort",
    auth_name: "Name",
    auth_name_placeholder: "Ihr Name",
    auth_phone: "Telefon",
    auth_phone_placeholder: "Ihre Telefonnummer",
    auth_confirm_password: "Passwort bestätigen",
    auth_confirm_password_placeholder: "Passwort wiederholen",
    auth_logging_in: "Anmelden...",
    auth_signing_up: "Registrieren...",
    auth_login_success: "Angemeldet!",
    auth_login_fail: "Anmeldung fehlgeschlagen.",
    auth_signup_success: "Konto erstellt! Bitte Profil vervollständigen.",
    auth_signup_fail: "Registrierung fehlgeschlagen.",
    auth_google_signin: "Mit Google anmelden",
    auth_google_signup: "Mit Google registrieren",
    auth_or: "oder",
    auth_password_mismatch: "Passwörter stimmen nicht überein.",
    auth_agree_required: "Bitte stimmen Sie den Bedingungen zu.",
    auth_terms_agree: "Ich stimme den AGB und der Datenschutzerklärung zu.",
    auth_benefits_title: "Mitgliedsvorteile",
    auth_benefit_1: "10% Willkommensgutschein bei Registrierung",
    auth_benefit_2: "3% Bonuspunkte auf jeden Einkauf",
    auth_benefit_3: "Spezielle Geschenke im Geburtstagsmonat",
    cp_title: "Profil vervollständigen",
    cp_subtitle: "Bitte geben Sie Ihre Lieferadresse ein, um mit dem Einkaufen zu beginnen.",
    cp_country: "Land",
    cp_country_code: "Ländercode",
    cp_address: "Adresse",
    cp_detail_address: "Adresszusatz",
    cp_shipping_address: "Lieferadresse",
    cp_customs_number: "Zollnummer",
    cp_customs_hint: "Erforderlich für internationalen Versand",
    cp_postal: "PLZ",
    cp_city: "Stadt / Bundesland",
    cp_phone: "Telefon",
    cp_save: "Speichern & Weiter",
    cp_saving: "Speichern...",
    cp_skip: "Später ausfüllen",
    cp_success: "Profil gespeichert!",
    cp_fail: "Fehler beim Speichern.",

    co_shipping: "Lieferadresse",
    co_recipient: "Empfänger",
    co_phone: "Telefon",
    co_address: "Adresse",
    co_detail_address: "Adresszusatz",
    co_postal: "PLZ",
    co_city: "Stadt",
    co_payment: "Zahlungsmethode",
    co_card: "Kreditkarte",
    co_bank: "Überweisung",
    co_kakao: "KakaoPay",
    co_naver: "NaverPay",
    co_summary: "Bestellübersicht",
    co_coupon: "Gutscheincode",
    co_apply: "Anwenden",
    co_discount: "Rabatt",
    co_total: "Gesamt",
    co_processing: "Verarbeitung...",
    co_pay: "Bezahlen",
    co_login_required: "Bitte melden Sie sich an.",
    co_cart_empty: "Ihr Warenkorb ist leer.",
    co_invalid_coupon: "Ungültiger Gutschein.",
    co_min_order: "Mindestbestellwert ist",
    co_coupon_applied: "Gutschein angewendet!",
    co_discount_amount: "Rabatt",
    co_order_success: "Bestellung aufgegeben!",
    co_order_fail: "Bestellung fehlgeschlagen.",

    mp_title: "Mein Konto",
    mp_logout: "Abmelden",
    mp_orders: "Bestellungen",
    mp_wishlist: "Wunschliste",
    mp_profile: "Profil",
    mp_no_orders: "Keine Bestellungen.",
    mp_order_date: "Bestellung",
    mp_subtotal: "Zwischensumme",
    mp_no_wishlist: "Wunschliste leer.",
    mp_email: "E-Mail",
    mp_name: "Name",
    mp_phone: "Telefon",
    mp_login_required: "Bitte melden Sie sich an.",

    status_pending: "Ausstehend",
    status_confirmed: "Bestätigt",
    status_shipping: "Im Versand",
    status_delivered: "Zugestellt",
    status_cancelled: "Storniert",

    contact_tagline: "Kontakt",
    contact_title: "Kontaktieren Sie uns",
    contact_subtitle: "Haben Sie Fragen? Wir sind für Sie da.",
    contact_send: "Nachricht senden",
    contact_name: "Name",
    contact_email: "E-Mail",
    contact_phone: "Telefon",
    contact_message: "Nachricht",
    contact_message_placeholder: "Was möchten Sie uns mitteilen...",
    contact_submit: "Senden",
    contact_info: "Kontaktinformationen",
    contact_address_title: "Hauptsitz",
    contact_address_value: "123 Teheranro, Gangnam-gu\nSeoul, Südkorea",
    contact_phone_title: "Telefon",
    contact_phone_value: "Zentrale: +82-2-1234-5678\nSupport: 1588-1234",
    contact_email_title: "E-Mail",
    contact_email_value: "Allgemein: contact@bloomandgrace.com\nPartner: partnership@bloomandgrace.com",
    contact_hours_title: "Öffnungszeiten",
    contact_hours_value: "Mo-Fr: 10:00 - 18:00\nMittagspause: 12:00 - 13:00\nWochenende: Geschlossen",
    contact_visit: "Besuch buchen",
    contact_visit_desc: "Reservieren Sie vorab für eine bequemere Beratung.",
    contact_reserve: "Reservieren",
    contact_map: "Anfahrt",
    contact_map_desc: "Kartenbereich",

    qa_tagline: "Häufige Fragen",
    qa_title: "Fragen & Antworten",
    qa_subtitle: "Wir haben die häufigsten Fragen zusammengestellt. Kontaktieren Sie uns gerne.",
    qa_not_found: "Keine Antwort gefunden?",
    qa_not_found_desc: "Kontaktieren Sie uns und wir helfen gerne.",
    qa_email_btn: "E-Mail senden",
    qa_phone_btn: "Anrufen",
    qa_cat_product: "Produkte",
    qa_cat_shipping: "Versand & Bestellungen",
    qa_cat_returns: "Rückgabe & Umtausch",
    qa_cat_membership: "Mitgliedschaft",
    qa_cat_sustainability: "Nachhaltigkeit",
    qa_cat_support: "Kundenservice",
    qa_q1: "Aus welchen Inhaltsstoffen bestehen Ihre Produkte?",
    qa_a1: "Unsere Produkte werden mit premium koreanischen Naturzutaten hergestellt.",
    qa_q2: "Wie wähle ich Produkte für meinen Hauttyp?",
    qa_a2: "Jede Produktseite zeigt den empfohlenen Hauttyp an.",
    qa_q3: "Testen Sie an Tieren?",
    qa_a3: "Nein. Bloom & Grace ist cruelty-free zertifiziert.",
    qa_q4: "Wie lange dauert der Versand?",
    qa_a4: "Inlandsversand dauert 2-3 Werktage.",
    qa_q5: "Was kostet der Versand?",
    qa_a5: "Kostenloser Versand ab 50€ Bestellwert.",
    qa_q6: "Kann ich meine Bestellung stornieren?",
    qa_a6: "Ja, bis zur Versandvorbereitung.",
    qa_q7: "Wie gebe ich ein Produkt zurück?",
    qa_a7: "Rückgabe innerhalb von 7 Tagen für ungeöffnete Produkte.",
    qa_q8: "Ich habe ein defektes Produkt erhalten.",
    qa_a8: "Volle Rückerstattung oder Umtausch für defekte Produkte.",
    qa_q9: "Gibt es Vorteile bei der Registrierung?",
    qa_a9: "Neue Mitglieder erhalten einen 10% Rabattgutschein.",
    qa_q10: "Wie nutze ich Bonuspunkte?",
    qa_a10: "Punkte können ab 1€ wie Bargeld eingesetzt werden.",
    qa_q11: "Verwenden Sie umweltfreundliche Verpackungen?",
    qa_a11: "Ja, alle Produkte werden mit recycelbaren Materialien verpackt.",
    qa_q12: "Gibt es Nachfüllprodukte?",
    qa_a12: "Ja, Hauptpflegelinien bieten Nachfüllungen mit 20% Rabatt.",
    qa_q13: "Wann ist der Kundenservice erreichbar?",
    qa_a13: "Montag bis Freitag von 10 bis 18 Uhr.",
    qa_q14: "Gibt es persönliche Beratung?",
    qa_a14: "Ja, per Chat oder E-Mail an contact@bloomandgrace.com.",

    currency: "€",
    currency_suffix: "",
  },
  fr: {
    nav_home: "Accueil",
    nav_products: "Produits",
    nav_all_products: "Tous les Produits",
    nav_skincare: "Soins",
    nav_makeup: "Maquillage",
    nav_haircare: "Cheveux",
    nav_fragrance: "Parfum",
    nav_bodycare: "Corps",
    nav_health: "Santé",
    nav_tools: "Accessoires",
    nav_brand_story: "Notre Histoire",
    nav_qa: "Q&R",
    nav_ranking: "Classement",
    nav_sale: "Soldes",
    nav_routine: "Votre Routine",
    nav_contact: "Contact",
    nav_admin: "Admin",
    nav_menu: "Menu",
    nav_mypage: "Mon Compte",
    nav_login: "Connexion",
    hero_tagline: "Beauté Coréenne Premium",
    hero_title: "Bloom & Grace",
    hero_subtitle: "Inspiré par la sagesse de la beauté coréenne. Élaboré avec les meilleurs ingrédients naturels pour sublimer votre élégance.",
    hero_shop: "Découvrir la Collection",
    hero_story: "Notre Histoire",
    featured_tagline: "HOT PRODUCT",
    featured_title: "Produits Phares",
    featured_subtitle: "L'essentiel beauté inspiré des cosmétiques coréens",
    featured_view_all: "Voir Tous les Produits",
    footer_desc: "Une marque inspirée de la sagesse beauté coréenne. Élaborée avec les meilleurs ingrédients naturels.",
    footer_products: "Produits",
    footer_brand: "Marque",
    footer_support: "Support",
    footer_rights: "Tous droits réservés.",
    products_title: "Tous les Produits",
    products_subtitle: "Collection de cosmétiques coréens premium",
    products_search: "Rechercher...",
    products_all: "Tout",
    products_no_results: "Aucun produit trouvé.",
    pd_add_to_cart: "Ajouter au panier",
    pd_review_section: "Avis",
    pd_all: "Tout",
    pd_write_review: "Écrire un avis",
    pd_review_title: "Titre",
    pd_review_content: "Écrivez votre avis...",
    pd_submit_review: "Envoyer",
    pd_no_reviews: "Aucun avis pour le moment.",
    pd_anonymous: "Anonyme",
    pd_loading: "Chargement...",
    pd_not_found: "Produit introuvable.",
    cart_title: "Panier",
    cart_empty: "Votre panier est vide",
    cart_total: "Total",
    cart_checkout: "Commander",
    cart_added: "Ajouté au panier !",
    co_title: "Commande",
    co_total: "Total",
    co_pay: "Payer",
    currency: "€",
    currency_suffix: "",
  },
  pt: {
    nav_home: "Início",
    nav_products: "Produtos",
    nav_all_products: "Todos os Produtos",
    nav_skincare: "Skincare",
    nav_makeup: "Maquiagem",
    nav_haircare: "Cabelo",
    nav_fragrance: "Perfume",
    nav_bodycare: "Corpo",
    nav_health: "Saúde",
    nav_tools: "Acessórios",
    nav_brand_story: "Nossa História",
    nav_qa: "Q&A",
    nav_ranking: "Ranking",
    nav_sale: "Promoção",
    nav_routine: "Sua Rotina",
    nav_contact: "Contato",
    nav_admin: "Admin",
    nav_menu: "Menu",
    nav_mypage: "Minha Conta",
    nav_login: "Entrar",
    hero_tagline: "Beleza Coreana Premium",
    hero_title: "Bloom & Grace",
    hero_subtitle: "Inspirado na sabedoria da beleza coreana. Elaborado com os melhores ingredientes naturais para realçar sua elegância.",
    hero_shop: "Ver Coleção",
    hero_story: "Nossa História",
    featured_tagline: "HOT PRODUCT",
    featured_title: "Produtos em Destaque",
    featured_subtitle: "Essenciais de beleza inspirados nos cosméticos coreanos",
    featured_view_all: "Ver Todos os Produtos",
    footer_desc: "Marca inspirada na sabedoria da beleza coreana. Elaborada com os melhores ingredientes naturais.",
    footer_products: "Produtos",
    footer_brand: "Marca",
    footer_support: "Suporte",
    footer_rights: "Todos os direitos reservados.",
    products_title: "Todos os Produtos",
    products_subtitle: "Coleção de cosméticos coreanos premium",
    products_search: "Buscar...",
    products_all: "Todos",
    products_no_results: "Nenhum produto encontrado.",
    pd_add_to_cart: "Adicionar ao carrinho",
    pd_review_section: "Avaliações",
    pd_all: "Tudo",
    pd_write_review: "Escrever avaliação",
    pd_review_title: "Título",
    pd_review_content: "Escreva sua avaliação...",
    pd_submit_review: "Enviar",
    pd_no_reviews: "Sem avaliações ainda.",
    pd_anonymous: "Anônimo",
    pd_loading: "Carregando...",
    pd_not_found: "Produto não encontrado.",
    cart_title: "Carrinho",
    cart_empty: "Seu carrinho está vazio",
    cart_total: "Total",
    cart_checkout: "Finalizar",
    cart_added: "Adicionado ao carrinho!",
    co_title: "Checkout",
    co_total: "Total",
    co_pay: "Pagar",
    currency: "R$",
    currency_suffix: "",
  },
  ar: {
    nav_home: "الرئيسية",
    nav_products: "المنتجات",
    nav_all_products: "كل المنتجات",
    nav_skincare: "العناية بالبشرة",
    nav_makeup: "المكياج",
    nav_haircare: "العناية بالشعر",
    nav_fragrance: "العطور",
    nav_bodycare: "العناية بالجسم",
    nav_health: "الصحة",
    nav_tools: "أدوات الجمال",
    nav_brand_story: "قصتنا",
    nav_qa: "أسئلة وأجوبة",
    nav_ranking: "الأكثر شعبية",
    nav_sale: "تخفيضات",
    nav_routine: "أنشئ روتينك",
    nav_contact: "اتصل بنا",
    nav_admin: "المسؤول",
    nav_menu: "القائمة",
    nav_mypage: "حسابي",
    nav_login: "تسجيل الدخول",
    hero_tagline: "جمال كوري فاخر",
    hero_title: "Bloom & Grace",
    hero_subtitle: "مستوحى من حكمة الجمال الكوري. مصنوع من أجود مكونات الطبيعة لإبراز أناقتك.",
    hero_shop: "تسوق المجموعة",
    hero_story: "قصتنا",
    featured_tagline: "HOT PRODUCT",
    featured_title: "المنتجات المميزة",
    featured_subtitle: "أساسيات الجمال المستوحاة من مستحضرات التجميل الكورية",
    featured_view_all: "عرض كل المنتجات",
    footer_desc: "علامة تجارية مستوحاة من حكمة الجمال الكوري. مصنوعة من أجود مكونات الطبيعة.",
    footer_products: "المنتجات",
    footer_brand: "العلامة التجارية",
    footer_support: "الدعم",
    footer_rights: "جميع الحقوق محفوظة.",
    products_title: "كل المنتجات",
    products_subtitle: "مجموعة مستحضرات التجميل الكورية الفاخرة",
    products_search: "بحث...",
    products_all: "الكل",
    products_no_results: "لا توجد منتجات.",
    pd_add_to_cart: "أضف إلى السلة",
    pd_review_section: "التقييمات",
    pd_all: "الكل",
    pd_write_review: "اكتب تقييمًا",
    pd_review_title: "العنوان",
    pd_review_content: "اكتب تقييمك...",
    pd_submit_review: "إرسال",
    pd_no_reviews: "لا توجد تقييمات بعد.",
    pd_anonymous: "مجهول",
    pd_loading: "جار التحميل...",
    pd_not_found: "المنتج غير موجود.",
    cart_title: "سلة التسوق",
    cart_empty: "سلتك فارغة",
    cart_total: "المجموع",
    cart_checkout: "إتمام الشراء",
    cart_added: "تمت الإضافة إلى السلة!",
    co_title: "الدفع",
    co_total: "المجموع",
    co_pay: "ادفع",
    currency: "$",
    currency_suffix: "",
  },
  ja: {
    nav_home: "ホーム",
    nav_products: "商品",
    nav_all_products: "すべての商品",
    nav_skincare: "スキンケア",
    nav_makeup: "メイクアップ",
    nav_haircare: "ヘアケア",
    nav_fragrance: "フレグランス",
    nav_bodycare: "ボディケア",
    nav_health: "健康食品",
    nav_tools: "ビューティーツール",
    nav_brand_story: "ブランドストーリー",
    nav_qa: "Q&A",
    nav_ranking: "ランキング",
    nav_sale: "セール",
    nav_routine: "あなたのルーティン",
    nav_contact: "お問い合わせ",
    nav_admin: "管理者",
    nav_menu: "メニュー",
    nav_mypage: "マイページ",
    nav_login: "ログイン",
    hero_tagline: "プレミアム韓国コスメ",
    hero_title: "Bloom & Grace",
    hero_subtitle: "韓国コスメの知恵を込めて。自然の最高の原料であなたの優雅さを完成させます。",
    hero_shop: "コレクションを見る",
    hero_story: "ブランドストーリー",
    featured_tagline: "HOT PRODUCT",
    featured_title: "おすすめ商品",
    featured_subtitle: "韓国コスメを纏うビューティーエッセンシャル",
    featured_view_all: "すべての商品を見る",
    footer_desc: "韓国コスメの知恵を込めたブランド。自然の最高の原料で優雅さを完成させます。",
    footer_products: "商品",
    footer_brand: "ブランド",
    footer_support: "サポート",
    footer_rights: "無断複写・転載を禁じます。",
    products_title: "すべての商品",
    products_subtitle: "プレミアム韓国コスメコレクション",
    products_search: "商品を検索...",
    products_all: "すべて",
    products_no_results: "商品が見つかりません。",
    pd_add_to_cart: "カートに追加",
    pd_review_section: "レビュー",
    pd_all: "すべて",
    pd_write_review: "レビューを書く",
    pd_review_title: "タイトル",
    pd_review_content: "レビューを書いてください...",
    pd_submit_review: "送信",
    pd_no_reviews: "まだレビューはありません。",
    pd_anonymous: "匿名",
    pd_loading: "読み込み中...",
    pd_not_found: "商品が見つかりません。",
    cart_title: "ショッピングカート",
    cart_empty: "カートは空です",
    cart_total: "合計",
    cart_checkout: "ご購入手続きへ",
    cart_added: "カートに追加されました！",
    co_title: "お支払い",
    co_total: "合計",
    co_pay: "支払う",
    currency: "¥",
    currency_suffix: "",
  },
};


type TranslationKey = keyof typeof translations.en;

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: TranslationKey) => string;
  formatPrice: (price: number) => string;
}

const LanguageContext = createContext<LanguageContextType>({} as LanguageContextType);

export const useLanguage = () => useContext(LanguageContext);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem("bloom-lang");
    const allowed: Language[] = ["en", "es", "de", "fr", "pt", "ja", "ar"];
    return allowed.includes(saved as Language) ? (saved as Language) : "en";
  });

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem("bloom-lang", lang);
  };

  const t = (key: TranslationKey): string => {
    return (translations[language] as any)?.[key] || translations.en[key] || key;
  };

  const formatPrice = (price: number): string => {
    const curr = translations[language] as any;
    const rate =
      language === "de" || language === "fr" ? 1400 :
      language === "pt" ? 260 :
      language === "ja" ? 10 : 1300;
    const converted = language === "ja" ? Math.round(price / rate).toString() : (price / rate).toFixed(2);
    return `${curr.currency}${converted}${curr.currency_suffix || ""}`;
  };


  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t, formatPrice }}>
      {children}
    </LanguageContext.Provider>
  );
};
