import { createContext, useContext, useState, ReactNode } from "react";

export type Language = "en" | "ko" | "es" | "de";

const translations = {
  en: {
    // Navigation
    nav_home: "Home",
    nav_products: "Products",
    nav_all_products: "All Products",
    nav_skincare: "Skincare",
    nav_skincare_desc: "Skin care products",
    nav_makeup: "Makeup",
    nav_makeup_desc: "Color cosmetics",
    nav_haircare: "Hair Care",
    nav_haircare_desc: "Hair management",
    nav_fragrance: "Fragrance",
    nav_fragrance_desc: "Signature perfumes",
    nav_bodycare: "Body Care",
    nav_bodycare_desc: "Body care products",
    nav_health: "Health Foods",
    nav_health_desc: "Health supplements",
    nav_brand_story: "Brand Story",
    nav_qa: "Q&A",
    nav_contact: "Contact",
    nav_admin: "Admin",
    nav_menu: "Menu",
    nav_mypage: "My Page",
    nav_login: "Sign In",

    // Hero
    hero_tagline: "Premium Korean Beauty",
    hero_title: "Bloom & Grace",
    hero_subtitle: "Premium cosmetics infused with Korean beauty wisdom. Crafted with nature's finest ingredients to complete your elegance.",
    hero_shop: "Shop Collection",
    hero_story: "Our Story",

    // Featured Products
    featured_tagline: "Signature Collection",
    featured_title: "Featured Products",
    featured_subtitle: "Premium beauty essentials embracing Korean beauty",
    featured_view_all: "View All Products",

    // About
    about_tagline: "Our Philosophy",
    about_title: "Our Story",
    about_p1: "Welcome to Bloom & Grace, where Korean beauty wisdom meets autumn's gentle embrace. Like walking through a serene garden kissed by fall's golden light, where soft pink petals rest on verdant grass, our boutique is a sanctuary of refined elegance.",
    about_p2: "Every product in our collection embodies the meticulous care of Korean beauty traditions—infused with natural botanicals, autumn herbs, and the gentle touch of nature's finest ingredients. We believe beauty should feel as luxurious and comforting as the warm glow of an autumn afternoon, where every detail whispers sophistication.",
    about_p3: "From our signature formulations to our thoughtfully designed packaging, each element is crafted to enhance your natural radiance while nourishing your skin with the purity of nature. Join us in celebrating beauty that blooms gracefully from within, just like the changing seasons.",
    about_since: "Crafted with care since 2024",

    // Footer
    footer_desc: "Premium cosmetics brand embracing Korean beauty wisdom. Crafted with nature's finest ingredients to complete your elegance.",
    footer_products: "Products",
    footer_new: "New Arrivals",
    footer_bestseller: "Bestsellers",
    footer_brand: "Brand",
    footer_store: "Store Info",
    footer_sustainability: "Sustainability",
    footer_ingredients: "Ingredients Story",
    footer_careers: "Careers",
    footer_support: "Support",
    footer_faq: "FAQ",
    footer_shipping: "Shipping Info",
    footer_returns: "Returns & Exchanges",
    footer_terms: "Terms of Service",
    footer_rights: "All rights reserved.",
    footer_cs: "Customer Service: 1588-1234 | Email: contact@bloomandgrace.com",

    // Products page
    products_title: "All Products",
    products_subtitle: "Premium Korean cosmetics collection",
    products_search: "Search products...",
    products_search_btn: "Search",
    products_all: "All",
    products_category: "Category",
    products_popular: "Popular",
    products_newest: "Newest",
    products_price_low: "Price: Low to High",
    products_price_high: "Price: High to Low",
    products_rating: "Top Rated",
    products_all_prices: "All Prices",
    products_under_20k: "Under $20",
    products_20k_50k: "$20 - $50",
    products_over_50k: "Over $50",
    products_no_results: "No products found.",

    // Product Detail
    pd_reviews: "reviews",
    pd_stock: "In Stock",
    pd_out_of_stock: "Out of Stock",
    pd_add_to_cart: "Add to Cart",
    pd_review_section: "Reviews",
    pd_all: "All",
    pd_above: "& above",
    pd_write_review: "Write a Review",
    pd_review_title: "Title",
    pd_review_content: "Write your review...",
    pd_submit_review: "Submit Review",
    pd_no_reviews: "No reviews yet.",
    pd_anonymous: "Anonymous",
    pd_loading: "Loading...",
    pd_not_found: "Product not found.",
    pd_already_reviewed: "You've already reviewed this product.",
    pd_review_fail: "Failed to submit review.",
    pd_review_success: "Review submitted successfully!",

    // Cart
    cart_title: "Shopping Cart",
    cart_empty: "Your cart is empty",
    cart_total: "Total",
    cart_checkout: "Checkout",
    cart_added: "Added to cart!",
    cart_login_required: "Please sign in first.",

    // Product Card
    pc_add_to_cart: "Add to Cart",

    // Auth
    auth_title: "Bloom & Grace",
    auth_subtitle: "Premium Korean Cosmetics",
    auth_login: "Sign In",
    auth_signup: "Join Us",
    auth_email: "Email",
    auth_email_placeholder: "Enter your email",
    auth_password: "Password",
    auth_password_placeholder: "Enter your password",
    auth_name: "Name",
    auth_name_placeholder: "Enter your name",
    auth_phone: "Phone",
    auth_phone_placeholder: "Enter your phone number",
    auth_confirm_password: "Confirm Password",
    auth_confirm_password_placeholder: "Re-enter your password",
    auth_logging_in: "Signing in...",
    auth_signing_up: "Signing up...",
    auth_login_success: "Signed in successfully!",
    auth_login_fail: "Failed to sign in.",
    auth_signup_success: "Account created! Please complete your profile.",
    auth_signup_fail: "Failed to create account.",
    auth_google_signin: "Sign in with Google",
    auth_google_signup: "Sign up with Google",
    auth_or: "or",
    auth_password_mismatch: "Passwords do not match.",
    auth_agree_required: "Please agree to the terms.",
    auth_terms_agree: "I agree to the Terms of Service and Privacy Policy.",
    auth_benefits_title: "Member Benefits",
    auth_benefit_1: "10% welcome coupon on sign-up",
    auth_benefit_2: "3% reward points on every purchase",
    auth_benefit_3: "Birthday month special gifts & coupons",
    // Profile Completion
    cp_title: "Complete Your Profile",
    cp_subtitle: "Please fill in your shipping details to start shopping.",
    cp_country: "Country",
    cp_country_code: "Country Code",
    cp_address: "Address",
    cp_detail_address: "Detail Address",
    cp_shipping_address: "Shipping Address",
    cp_customs_number: "Customs Number (PCCC)",
    cp_customs_hint: "Required for international shipping",
    cp_postal: "Postal Code",
    cp_city: "City / State",
    cp_phone: "Phone Number",
    cp_save: "Save & Continue",
    cp_saving: "Saving...",
    cp_skip: "Skip for now",
    cp_success: "Profile saved successfully!",
    cp_fail: "Failed to save profile.",

    // Checkout
    co_title: "Checkout",
    co_shipping: "Shipping Address",
    co_recipient: "Recipient",
    co_phone: "Phone",
    co_address: "Address",
    co_detail_address: "Detail Address",
    co_postal: "Postal Code",
    co_city: "City",
    co_payment: "Payment Method",
    co_card: "Credit Card",
    co_bank: "Bank Transfer",
    co_kakao: "KakaoPay",
    co_naver: "NaverPay",
    co_summary: "Order Summary",
    co_coupon: "Coupon Code",
    co_apply: "Apply",
    co_discount: "Discount",
    co_total: "Total",
    co_processing: "Processing...",
    co_pay: "Pay",
    co_login_required: "Please sign in first.",
    co_cart_empty: "Your cart is empty.",
    co_invalid_coupon: "Invalid coupon.",
    co_min_order: "Minimum order amount is",
    co_coupon_applied: "Coupon applied!",
    co_discount_amount: "discount",
    co_order_success: "Order placed successfully!",
    co_order_fail: "Failed to place order.",

    // MyPage
    mp_title: "My Page",
    mp_logout: "Sign Out",
    mp_orders: "Orders",
    mp_wishlist: "Wishlist",
    mp_profile: "Profile",
    mp_no_orders: "No orders yet.",
    mp_order_date: "Order",
    mp_subtotal: "Subtotal",
    mp_no_wishlist: "No items in wishlist.",
    mp_email: "Email",
    mp_name: "Name",
    mp_phone: "Phone",
    mp_login_required: "Please sign in first.",

    // Order statuses
    status_pending: "Pending",
    status_confirmed: "Confirmed",
    status_shipping: "Shipping",
    status_delivered: "Delivered",
    status_cancelled: "Cancelled",

    // Contact
    contact_tagline: "Get in Touch",
    contact_title: "Contact Us",
    contact_subtitle: "Have questions or need help? We're here for you.",
    contact_send: "Send a Message",
    contact_name: "Name",
    contact_email: "Email",
    contact_phone: "Phone",
    contact_message: "Message",
    contact_message_placeholder: "Tell us what's on your mind...",
    contact_submit: "Send Message",
    contact_info: "Contact Information",
    contact_address_title: "Headquarters",
    contact_address_value: "123 Teheranro, Gangnam-gu\nSeoul, South Korea",
    contact_phone_title: "Phone",
    contact_phone_value: "Main: +82-2-1234-5678\nSupport: 1588-1234",
    contact_email_title: "Email",
    contact_email_value: "General: contact@bloomandgrace.com\nPartners: partnership@bloomandgrace.com",
    contact_hours_title: "Business Hours",
    contact_hours_value: "Weekdays: 10:00 AM - 6:00 PM\nLunch: 12:00 PM - 1:00 PM\nWeekends & Holidays: Closed",
    contact_visit: "Book a Visit",
    contact_visit_desc: "Reserve ahead for a more convenient consultation experience.",
    contact_reserve: "Reserve",
    contact_map: "Directions",
    contact_map_desc: "Map area (Google Maps or Kakao Map integration)",

    // QA
    qa_tagline: "Frequently Asked Questions",
    qa_title: "Q&A",
    qa_subtitle: "We've gathered the most commonly asked questions. Feel free to contact us for anything else.",
    qa_not_found: "Couldn't find your answer?",
    qa_not_found_desc: "Contact our support team and we'll be happy to help.",
    qa_email_btn: "Email Us",
    qa_phone_btn: "Call Us",
    // QA Categories
    qa_cat_product: "Products",
    qa_cat_shipping: "Shipping & Orders",
    qa_cat_returns: "Returns & Exchanges",
    qa_cat_membership: "Membership & Benefits",
    qa_cat_sustainability: "Sustainability",
    qa_cat_support: "Customer Support",
    // QA Questions
    qa_q1: "What ingredients are your products made of?",
    qa_a1: "Our products are made with premium Korean natural ingredients including green tea extract, rose essence, yuzu extract, and pearl powder. We never use parabens, artificial fragrances, or animal-derived ingredients.",
    qa_q2: "How do I choose products for my skin type?",
    qa_a2: "Each product page displays the recommended skin type. We offer gentle lines for sensitive skin, intensive moisture lines for dry skin, and sebum care lines for oily skin. Please don't hesitate to contact us.",
    qa_q3: "Do you test on animals?",
    qa_a3: "Absolutely not. Bloom & Grace is committed to being cruelty-free, and all our products are certified. We pursue ethical and sustainable beauty.",
    qa_q4: "How long does shipping take?",
    qa_a4: "Domestic shipping arrives within 2-3 business days. International shipping takes 5-10 business days. Remote areas may require 1-2 additional days. Tracking numbers are sent via text and email.",
    qa_q5: "What are the shipping costs?",
    qa_a5: "Free domestic shipping on orders over $50. Orders under $50 have a $3 shipping fee. International shipping varies by country and is calculated at checkout.",
    qa_q6: "Can I cancel or modify my order?",
    qa_a6: "Orders can be cancelled or modified through customer service until the 'preparing shipment' stage. After shipping begins, you'll need to use the returns/exchange process.",
    qa_q7: "How do I return or exchange a product?",
    qa_a7: "Returns and exchanges are available within 7 days of receipt for unopened products. Contact customer service for return address and procedures. Return shipping for change of mind is the customer's responsibility.",
    qa_q8: "I received a defective product.",
    qa_a8: "We offer full refunds or exchanges for defective products. Please contact customer service with photos, and we'll handle it promptly. We cover the return shipping cost.",
    qa_q9: "Are there sign-up benefits?",
    qa_a9: "New members receive a 10% discount coupon, and 3% of purchases are accumulated as points. Special coupons and gifts are provided during your birthday month.",
    qa_q10: "How do I use reward points?",
    qa_a10: "Points can be used starting from $1 and work like cash for product purchases. Points are valid for 2 years from the date earned.",
    qa_q11: "Do you use eco-friendly packaging?",
    qa_a11: "Yes, all products are packaged with recyclable materials and we minimize unnecessary plastic use. We use FSC-certified paper and biodegradable materials.",
    qa_q12: "Do you offer refill products?",
    qa_a12: "Main skincare lines offer refill products at 20% less than regular prices. You can return empty containers to our store for reward points.",
    qa_q13: "What are customer service hours?",
    qa_a13: "We operate weekdays from 10 AM to 6 PM, with a lunch break from 12 PM to 1 PM. Weekends and holidays are closed. Email inquiries are accepted 24/7.",
    qa_q14: "Is 1:1 consultation available?",
    qa_a14: "Yes, you can get personalized consultation via our website chat or email (contact@bloomandgrace.com). Feel free to ask about skin concerns, product recommendations, and more.",

    // Currency
    currency: "$",
    currency_suffix: "",
  },
  ko: {
    nav_home: "홈",
    nav_products: "제품",
    nav_all_products: "전체 제품",
    nav_skincare: "스킨케어",
    nav_skincare_desc: "피부 케어 제품",
    nav_makeup: "메이크업",
    nav_makeup_desc: "컬러 화장품",
    nav_haircare: "헤어케어",
    nav_haircare_desc: "모발 관리",
    nav_fragrance: "향수",
    nav_fragrance_desc: "시그니처 향수",
    nav_bodycare: "바디케어",
    nav_bodycare_desc: "바디 케어",
    nav_health: "건강식품",
    nav_health_desc: "건강 보조 식품",
    nav_brand_story: "브랜드 스토리",
    nav_qa: "Q&A",
    nav_contact: "문의하기",
    nav_admin: "관리자",
    nav_menu: "메뉴",
    nav_mypage: "마이페이지",
    nav_login: "로그인",

    hero_tagline: "Premium Korean Beauty",
    hero_title: "Bloom & Grace",
    hero_subtitle: "한국의 아름다움을 담은 프리미엄 화장품. 자연에서 온 귀한 성분으로 당신의 우아함을 완성합니다.",
    hero_shop: "컬렉션 보기",
    hero_story: "브랜드 스토리",

    featured_tagline: "Signature Collection",
    featured_title: "추천 상품",
    featured_subtitle: "한국의 아름다움을 담은 프리미엄 뷰티 에센셜",
    featured_view_all: "전체 상품 보기",

    about_tagline: "Our Philosophy",
    about_title: "Our Story",
    about_p1: "Bloom & Grace에 오신 것을 환영합니다. 한국 뷰티의 지혜가 가을의 부드러운 포옹을 만나는 곳입니다. 가을 황금빛으로 물든 고요한 정원을 거닐며, 부드러운 분홍 꽃잎이 푸른 잔디 위에 내려앉는 곳, 우리의 부티크는 세련된 우아함의 안식처입니다.",
    about_p2: "우리 컬렉션의 모든 제품은 한국 뷰티 전통의 세심한 관리를 담고 있습니다—천연 식물 성분, 가을 허브, 그리고 자연의 최고급 재료들의 부드러운 터치가 스며들어 있습니다. 아름다움은 가을 오후의 따뜻한 햇살처럼 럭셔리하고 편안해야 한다고 믿습니다.",
    about_p3: "시그니처 포뮬레이션부터 세심하게 디자인된 패키지까지, 모든 요소는 자연의 순수함으로 피부를 영양 공급하면서 당신의 자연스러운 빛남을 향상시키기 위해 만들어졌습니다. 변화하는 계절처럼 내면에서 우아하게 피어나는 아름다움을 함께 축하합시다.",
    about_since: "2024년부터 정성을 담아",

    footer_desc: "한국의 아름다움을 담은 프리미엄 화장품 브랜드. 자연에서 온 귀한 성분으로 당신의 우아함을 완성합니다.",
    footer_products: "제품",
    footer_new: "신제품",
    footer_bestseller: "베스트셀러",
    footer_brand: "브랜드",
    footer_store: "매장 안내",
    footer_sustainability: "지속가능성",
    footer_ingredients: "성분 이야기",
    footer_careers: "채용 정보",
    footer_support: "고객지원",
    footer_faq: "자주 묻는 질문",
    footer_shipping: "배송 안내",
    footer_returns: "교환/반품",
    footer_terms: "이용약관",
    footer_rights: "All rights reserved.",
    footer_cs: "고객센터: 1588-1234 | 이메일: contact@bloomandgrace.com",

    products_title: "전체 상품",
    products_subtitle: "프리미엄 한국 화장품 컬렉션",
    products_search: "상품 검색...",
    products_search_btn: "검색",
    products_all: "전체",
    products_category: "카테고리",
    products_popular: "인기순",
    products_newest: "최신순",
    products_price_low: "가격 낮은순",
    products_price_high: "가격 높은순",
    products_rating: "평점순",
    products_all_prices: "전체 가격",
    products_under_20k: "2만원 미만",
    products_20k_50k: "2만원~5만원",
    products_over_50k: "5만원 이상",
    products_no_results: "검색 결과가 없습니다.",

    pd_reviews: "개 리뷰",
    pd_stock: "재고",
    pd_out_of_stock: "품절",
    pd_add_to_cart: "장바구니 담기",
    pd_review_section: "리뷰",
    pd_all: "전체",
    pd_above: "점 이상",
    pd_write_review: "리뷰 작성",
    pd_review_title: "제목",
    pd_review_content: "리뷰를 작성해주세요",
    pd_submit_review: "리뷰 등록",
    pd_no_reviews: "아직 리뷰가 없습니다.",
    pd_anonymous: "익명",
    pd_loading: "로딩 중...",
    pd_not_found: "상품을 찾을 수 없습니다.",
    pd_already_reviewed: "이미 리뷰를 작성하셨습니다.",
    pd_review_fail: "리뷰 작성에 실패했습니다.",
    pd_review_success: "리뷰가 등록되었습니다!",

    cart_title: "장바구니",
    cart_empty: "장바구니가 비어있습니다",
    cart_total: "합계",
    cart_checkout: "주문하기",
    cart_added: "장바구니에 추가되었습니다!",
    cart_login_required: "로그인이 필요합니다.",

    pc_add_to_cart: "장바구니",

    auth_title: "Bloom & Grace",
    auth_subtitle: "프리미엄 한국 화장품",
    auth_login: "로그인",
    auth_signup: "회원가입",
    auth_email: "이메일",
    auth_email_placeholder: "이메일을 입력하세요",
    auth_password: "비밀번호",
    auth_password_placeholder: "비밀번호를 입력하세요",
    auth_name: "이름",
    auth_name_placeholder: "이름을 입력하세요",
    auth_phone: "연락처",
    auth_phone_placeholder: "연락처를 입력하세요",
    auth_confirm_password: "비밀번호 확인",
    auth_confirm_password_placeholder: "비밀번호를 다시 입력하세요",
    auth_logging_in: "로그인 중...",
    auth_signing_up: "가입 중...",
    auth_login_success: "로그인되었습니다!",
    auth_login_fail: "로그인에 실패했습니다.",
    auth_signup_success: "회원가입이 완료되었습니다! 배송 정보를 입력해주세요.",
    auth_signup_fail: "회원가입에 실패했습니다.",
    auth_google_signin: "Google로 로그인",
    auth_google_signup: "Google로 간편 가입",
    auth_or: "또는",
    auth_password_mismatch: "비밀번호가 일치하지 않습니다.",
    auth_agree_required: "약관에 동의해주세요.",
    auth_terms_agree: "이용약관 및 개인정보처리방침에 동의합니다.",
    auth_benefits_title: "회원 혜택",
    auth_benefit_1: "회원가입 시 10% 할인 쿠폰 즉시 지급",
    auth_benefit_2: "구매 금액의 3% 적립금 자동 적립",
    auth_benefit_3: "생일 달 특별 쿠폰 및 선물 제공",
    cp_title: "배송 정보 입력",
    cp_subtitle: "쇼핑을 시작하기 위해 배송 정보를 입력해주세요.",
    cp_country: "국가",
    cp_country_code: "국가 코드",
    cp_address: "주소",
    cp_detail_address: "상세주소",
    cp_shipping_address: "배송지 주소",
    cp_customs_number: "통관번호 (개인통관고유부호)",
    cp_customs_hint: "해외 배송 시 필요합니다",
    cp_postal: "우편번호",
    cp_city: "시/도",
    cp_phone: "연락처",
    cp_save: "저장 후 계속",
    cp_saving: "저장 중...",
    cp_skip: "나중에 입력",
    cp_success: "프로필이 저장되었습니다!",
    cp_fail: "프로필 저장에 실패했습니다.",

    co_title: "주문하기",
    co_shipping: "배송지 정보",
    co_recipient: "수령인",
    co_phone: "연락처",
    co_address: "주소",
    co_detail_address: "상세주소",
    co_postal: "우편번호",
    co_city: "도시",
    co_payment: "결제 수단",
    co_card: "신용카드",
    co_bank: "계좌이체",
    co_kakao: "카카오페이",
    co_naver: "네이버페이",
    co_summary: "주문 요약",
    co_coupon: "쿠폰 코드",
    co_apply: "적용",
    co_discount: "할인",
    co_total: "합계",
    co_processing: "처리 중...",
    co_pay: "결제하기",
    co_login_required: "로그인이 필요합니다.",
    co_cart_empty: "장바구니가 비어있습니다.",
    co_invalid_coupon: "유효하지 않은 쿠폰입니다.",
    co_min_order: "최소 주문금액",
    co_coupon_applied: "쿠폰이 적용되었습니다!",
    co_discount_amount: "할인",
    co_order_success: "주문이 완료되었습니다!",
    co_order_fail: "주문에 실패했습니다.",

    mp_title: "마이페이지",
    mp_logout: "로그아웃",
    mp_orders: "주문내역",
    mp_wishlist: "찜 목록",
    mp_profile: "내 정보",
    mp_no_orders: "주문 내역이 없습니다.",
    mp_order_date: "주문",
    mp_subtotal: "합계",
    mp_no_wishlist: "찜한 상품이 없습니다.",
    mp_email: "이메일",
    mp_name: "이름",
    mp_phone: "연락처",
    mp_login_required: "로그인이 필요합니다.",

    status_pending: "주문 접수",
    status_confirmed: "주문 확인",
    status_shipping: "배송 중",
    status_delivered: "배송 완료",
    status_cancelled: "주문 취소",

    contact_tagline: "문의하기",
    contact_title: "Contact Us",
    contact_subtitle: "궁금하신 점이나 도움이 필요하신가요? 언제든 연락 주세요.",
    contact_send: "메시지 보내기",
    contact_name: "이름",
    contact_email: "이메일",
    contact_phone: "연락처",
    contact_message: "문의 내용",
    contact_message_placeholder: "궁금하신 점을 자세히 적어주세요...",
    contact_submit: "문의하기",
    contact_info: "연락처 정보",
    contact_address_title: "본사 주소",
    contact_address_value: "서울특별시 강남구 테헤란로 123\n블룸앤그레이스 빌딩 5층",
    contact_phone_title: "전화번호",
    contact_phone_value: "대표: 02-1234-5678\n고객센터: 1588-1234",
    contact_email_title: "이메일",
    contact_email_value: "일반 문의: contact@bloomandgrace.com\n제휴 문의: partnership@bloomandgrace.com",
    contact_hours_title: "운영 시간",
    contact_hours_value: "평일: 10:00 - 18:00\n점심시간: 12:00 - 13:00\n주말/공휴일 휴무",
    contact_visit: "방문 상담 예약",
    contact_visit_desc: "매장 방문 전 예약하시면 더욱 편리하게 상담받으실 수 있습니다.",
    contact_reserve: "예약하기",
    contact_map: "오시는 길",
    contact_map_desc: "지도 영역 (실제 구현 시 Google Maps 또는 Kakao Map 연동)",

    qa_tagline: "자주 묻는 질문",
    qa_title: "Q&A",
    qa_subtitle: "고객님들께서 가장 많이 물어보시는 질문들을 모았습니다. 궁금하신 점이 있으시다면 언제든 문의해주세요.",
    qa_not_found: "답변을 찾지 못하셨나요?",
    qa_not_found_desc: "고객센터로 문의해주시면 친절하게 답변드리겠습니다.",
    qa_email_btn: "이메일 문의하기",
    qa_phone_btn: "전화 상담하기",
    qa_cat_product: "제품 관련",
    qa_cat_shipping: "배송 및 주문",
    qa_cat_returns: "교환 및 반품",
    qa_cat_membership: "회원 및 혜택",
    qa_cat_sustainability: "지속가능성",
    qa_cat_support: "고객센터",
    qa_q1: "제품은 어떤 성분으로 만들어지나요?",
    qa_a1: "저희 제품은 한국산 프리미엄 천연 성분으로 제조됩니다. 녹차 추출물, 장미 에센스, 유자 추출물, 진주 파우더 등 자연에서 온 귀한 성분들을 사용하며, 파라벤, 인공향료, 동물성 성분은 일절 사용하지 않습니다.",
    qa_q2: "피부 타입에 맞는 제품을 어떻게 선택하나요?",
    qa_a2: "각 제품 페이지에 권장 피부 타입이 표시되어 있습니다. 민감성 피부를 위한 저자극 라인, 건성 피부를 위한 수분 집중 라인, 지성 피부를 위한 세범 케어 라인 등을 구분하여 제공합니다.",
    qa_q3: "동물 실험을 하나요?",
    qa_a3: "절대 하지 않습니다. Bloom & Grace는 동물 실험 반대를 원칙으로 하며, 모든 제품은 크루얼티 프리(Cruelty-Free) 인증을 받았습니다.",
    qa_q4: "배송은 얼마나 걸리나요?",
    qa_a4: "국내 배송은 주문 후 2-3일 이내 도착하며, 해외 배송은 5-10일 정도 소요됩니다. 제주도 및 도서산간 지역은 1-2일 추가될 수 있습니다.",
    qa_q5: "배송비는 얼마인가요?",
    qa_a5: "국내 배송은 50,000원 이상 구매 시 무료이며, 50,000원 미만은 3,000원의 배송비가 부과됩니다.",
    qa_q6: "주문 취소나 변경이 가능한가요?",
    qa_a6: "배송 준비 중 단계까지는 고객센터를 통해 취소 및 변경이 가능합니다.",
    qa_q7: "교환/반품은 어떻게 하나요?",
    qa_a7: "제품 수령 후 7일 이내 미개봉 상태에서 교환 및 반품이 가능합니다.",
    qa_q8: "불량 제품을 받았어요.",
    qa_a8: "불량 제품에 대해서는 전액 환불 또는 교환해드립니다.",
    qa_q9: "회원 가입 혜택이 있나요?",
    qa_a9: "신규 회원 가입 시 10% 할인 쿠폰을 드리며, 구매 금액의 3%가 적립금으로 적립됩니다.",
    qa_q10: "적립금은 어떻게 사용하나요?",
    qa_a10: "적립금은 1,000원 이상부터 사용 가능하며, 제품 구매 시 현금처럼 사용하실 수 있습니다.",
    qa_q11: "친환경 포장을 사용하나요?",
    qa_a11: "네, 모든 제품은 재활용 가능한 소재로 포장되며, 불필요한 플라스틱 사용을 최소화합니다.",
    qa_q12: "리필 제품이 있나요?",
    qa_a12: "주요 스킨케어 라인은 리필 제품을 제공하고 있으며, 일반 제품 대비 20% 저렴한 가격으로 구매하실 수 있습니다.",
    qa_q13: "고객센터 운영 시간은?",
    qa_a13: "평일 오전 10시부터 오후 6시까지 운영하며, 점심시간은 오후 12시~1시입니다.",
    qa_q14: "1:1 상담이 가능한가요?",
    qa_a14: "네, 웹사이트의 채팅 상담 또는 이메일(contact@bloomandgrace.com)로 1:1 맞춤 상담을 받으실 수 있습니다.",

    currency: "",
    currency_suffix: "원",
  },
  es: {
    nav_home: "Inicio",
    nav_products: "Productos",
    nav_all_products: "Todos los Productos",
    nav_skincare: "Cuidado de Piel",
    nav_skincare_desc: "Productos para el cuidado de la piel",
    nav_makeup: "Maquillaje",
    nav_makeup_desc: "Cosméticos de color",
    nav_haircare: "Cuidado Capilar",
    nav_haircare_desc: "Gestión del cabello",
    nav_fragrance: "Fragancias",
    nav_fragrance_desc: "Perfumes exclusivos",
    nav_bodycare: "Cuidado Corporal",
    nav_bodycare_desc: "Productos corporales",
    nav_health: "Suplementos",
    nav_health_desc: "Suplementos alimenticios",
    nav_brand_story: "Nuestra Historia",
    nav_qa: "Preguntas",
    nav_contact: "Contacto",
    nav_admin: "Admin",
    nav_menu: "Menú",
    nav_mypage: "Mi Página",
    nav_login: "Iniciar Sesión",

    hero_tagline: "Belleza Coreana Premium",
    hero_title: "Bloom & Grace",
    hero_subtitle: "Cosméticos premium con la sabiduría de la belleza coreana. Elaborados con los mejores ingredientes naturales para completar tu elegancia.",
    hero_shop: "Ver Colección",
    hero_story: "Nuestra Historia",

    featured_tagline: "Colección Exclusiva",
    featured_title: "Productos Destacados",
    featured_subtitle: "Esenciales de belleza premium que abrazan la belleza coreana",
    featured_view_all: "Ver Todos",

    about_tagline: "Nuestra Filosofía",
    about_title: "Nuestra Historia",
    about_p1: "Bienvenidos a Bloom & Grace, donde la sabiduría de la belleza coreana se encuentra con el suave abrazo del otoño. Como caminar por un jardín sereno besado por la luz dorada del otoño, nuestra boutique es un santuario de elegancia refinada.",
    about_p2: "Cada producto encarna el cuidado meticuloso de las tradiciones de belleza coreana—infundido con botánicos naturales, hierbas otoñales y el toque suave de los mejores ingredientes de la naturaleza.",
    about_p3: "Desde nuestras formulaciones exclusivas hasta nuestro empaque cuidadosamente diseñado, cada elemento está elaborado para realzar tu resplandor natural mientras nutre tu piel con la pureza de la naturaleza.",
    about_since: "Elaborado con cuidado desde 2024",

    footer_desc: "Marca de cosméticos premium que abraza la sabiduría de la belleza coreana.",
    footer_products: "Productos",
    footer_new: "Novedades",
    footer_bestseller: "Más Vendidos",
    footer_brand: "Marca",
    footer_store: "Tiendas",
    footer_sustainability: "Sostenibilidad",
    footer_ingredients: "Ingredientes",
    footer_careers: "Empleo",
    footer_support: "Soporte",
    footer_faq: "Preguntas Frecuentes",
    footer_shipping: "Envíos",
    footer_returns: "Devoluciones",
    footer_terms: "Términos",
    footer_rights: "Todos los derechos reservados.",
    footer_cs: "Atención al cliente: 1588-1234 | Email: contact@bloomandgrace.com",

    products_title: "Todos los Productos",
    products_subtitle: "Colección premium de cosméticos coreanos",
    products_search: "Buscar productos...",
    products_search_btn: "Buscar",
    products_all: "Todos",
    products_category: "Categoría",
    products_popular: "Popular",
    products_newest: "Más Reciente",
    products_price_low: "Menor Precio",
    products_price_high: "Mayor Precio",
    products_rating: "Mejor Valorado",
    products_all_prices: "Todos los Precios",
    products_under_20k: "Menos de $20",
    products_20k_50k: "$20 - $50",
    products_over_50k: "Más de $50",
    products_no_results: "No se encontraron productos.",

    pd_reviews: "reseñas",
    pd_stock: "En Stock",
    pd_out_of_stock: "Agotado",
    pd_add_to_cart: "Agregar al Carrito",
    pd_review_section: "Reseñas",
    pd_all: "Todas",
    pd_above: "y más",
    pd_write_review: "Escribir Reseña",
    pd_review_title: "Título",
    pd_review_content: "Escribe tu reseña...",
    pd_submit_review: "Enviar Reseña",
    pd_no_reviews: "Aún no hay reseñas.",
    pd_anonymous: "Anónimo",
    pd_loading: "Cargando...",
    pd_not_found: "Producto no encontrado.",
    pd_already_reviewed: "Ya has dejado una reseña.",
    pd_review_fail: "Error al enviar reseña.",
    pd_review_success: "¡Reseña enviada!",

    cart_title: "Carrito",
    cart_empty: "Tu carrito está vacío",
    cart_total: "Total",
    cart_checkout: "Pagar",
    cart_added: "¡Agregado al carrito!",
    cart_login_required: "Inicia sesión primero.",

    pc_add_to_cart: "Al Carrito",

    auth_title: "Bloom & Grace",
    auth_subtitle: "Cosméticos Coreanos Premium",
    auth_login: "Iniciar Sesión",
    auth_signup: "Únete",
    auth_email: "Correo",
    auth_email_placeholder: "Tu correo electrónico",
    auth_password: "Contraseña",
    auth_password_placeholder: "Tu contraseña",
    auth_name: "Nombre",
    auth_name_placeholder: "Tu nombre",
    auth_phone: "Teléfono",
    auth_phone_placeholder: "Tu número de teléfono",
    auth_confirm_password: "Confirmar Contraseña",
    auth_confirm_password_placeholder: "Repite tu contraseña",
    auth_logging_in: "Iniciando...",
    auth_signing_up: "Registrando...",
    auth_login_success: "¡Sesión iniciada!",
    auth_login_fail: "Error al iniciar sesión.",
    auth_signup_success: "¡Cuenta creada! Completa tu perfil.",
    auth_signup_fail: "Error al crear cuenta.",
    auth_google_signin: "Iniciar sesión con Google",
    auth_google_signup: "Registrarse con Google",
    auth_or: "o",
    auth_password_mismatch: "Las contraseñas no coinciden.",
    auth_agree_required: "Acepta los términos.",
    auth_terms_agree: "Acepto los Términos de Servicio y la Política de Privacidad.",
    auth_benefits_title: "Beneficios de Membresía",
    auth_benefit_1: "Cupón de bienvenida del 10%",
    auth_benefit_2: "3% de puntos en cada compra",
    auth_benefit_3: "Regalos especiales en tu cumpleaños",
    cp_title: "Completa tu Perfil",
    cp_subtitle: "Ingresa tus datos de envío para comenzar a comprar.",
    cp_country: "País",
    cp_country_code: "Código de País",
    cp_address: "Dirección",
    cp_detail_address: "Detalle de Dirección",
    cp_shipping_address: "Dirección de Envío",
    cp_customs_number: "Número de Aduanas",
    cp_customs_hint: "Requerido para envíos internacionales",
    cp_postal: "Código Postal",
    cp_city: "Ciudad / Estado",
    cp_phone: "Teléfono",
    cp_save: "Guardar y Continuar",
    cp_saving: "Guardando...",
    cp_skip: "Omitir por ahora",
    cp_success: "¡Perfil guardado!",
    cp_fail: "Error al guardar perfil.",

    co_title: "Pagar",
    co_shipping: "Dirección de Envío",
    co_recipient: "Destinatario",
    co_phone: "Teléfono",
    co_address: "Dirección",
    co_detail_address: "Detalle",
    co_postal: "Código Postal",
    co_city: "Ciudad",
    co_payment: "Método de Pago",
    co_card: "Tarjeta de Crédito",
    co_bank: "Transferencia",
    co_kakao: "KakaoPay",
    co_naver: "NaverPay",
    co_summary: "Resumen del Pedido",
    co_coupon: "Código de Cupón",
    co_apply: "Aplicar",
    co_discount: "Descuento",
    co_total: "Total",
    co_processing: "Procesando...",
    co_pay: "Pagar",
    co_login_required: "Inicia sesión primero.",
    co_cart_empty: "Tu carrito está vacío.",
    co_invalid_coupon: "Cupón inválido.",
    co_min_order: "Monto mínimo de pedido es",
    co_coupon_applied: "¡Cupón aplicado!",
    co_discount_amount: "descuento",
    co_order_success: "¡Pedido realizado!",
    co_order_fail: "Error al realizar pedido.",

    mp_title: "Mi Página",
    mp_logout: "Cerrar Sesión",
    mp_orders: "Pedidos",
    mp_wishlist: "Favoritos",
    mp_profile: "Perfil",
    mp_no_orders: "Sin pedidos aún.",
    mp_order_date: "Pedido",
    mp_subtotal: "Subtotal",
    mp_no_wishlist: "Sin favoritos.",
    mp_email: "Correo",
    mp_name: "Nombre",
    mp_phone: "Teléfono",
    mp_login_required: "Inicia sesión primero.",

    status_pending: "Pendiente",
    status_confirmed: "Confirmado",
    status_shipping: "En Envío",
    status_delivered: "Entregado",
    status_cancelled: "Cancelado",

    contact_tagline: "Contáctanos",
    contact_title: "Contacto",
    contact_subtitle: "¿Tienes preguntas? Estamos aquí para ayudarte.",
    contact_send: "Enviar Mensaje",
    contact_name: "Nombre",
    contact_email: "Correo",
    contact_phone: "Teléfono",
    contact_message: "Mensaje",
    contact_message_placeholder: "Cuéntanos qué necesitas...",
    contact_submit: "Enviar",
    contact_info: "Información de Contacto",
    contact_address_title: "Sede Central",
    contact_address_value: "123 Teheranro, Gangnam-gu\nSeúl, Corea del Sur",
    contact_phone_title: "Teléfono",
    contact_phone_value: "Principal: +82-2-1234-5678\nSoporte: 1588-1234",
    contact_email_title: "Correo",
    contact_email_value: "General: contact@bloomandgrace.com\nSocios: partnership@bloomandgrace.com",
    contact_hours_title: "Horario",
    contact_hours_value: "Lunes a Viernes: 10:00 - 18:00\nAlmuerzo: 12:00 - 13:00\nFines de semana: Cerrado",
    contact_visit: "Reservar Visita",
    contact_visit_desc: "Reserve con anticipación para una consulta más conveniente.",
    contact_reserve: "Reservar",
    contact_map: "Cómo Llegar",
    contact_map_desc: "Área del mapa",

    qa_tagline: "Preguntas Frecuentes",
    qa_title: "Preguntas y Respuestas",
    qa_subtitle: "Hemos reunido las preguntas más frecuentes. No dudes en contactarnos.",
    qa_not_found: "¿No encontraste tu respuesta?",
    qa_not_found_desc: "Contáctanos y te ayudaremos con gusto.",
    qa_email_btn: "Enviar Correo",
    qa_phone_btn: "Llamar",
    qa_cat_product: "Productos",
    qa_cat_shipping: "Envíos y Pedidos",
    qa_cat_returns: "Devoluciones",
    qa_cat_membership: "Membresía",
    qa_cat_sustainability: "Sostenibilidad",
    qa_cat_support: "Soporte",
    qa_q1: "¿De qué ingredientes están hechos sus productos?",
    qa_a1: "Nuestros productos están hechos con ingredientes naturales premium coreanos.",
    qa_q2: "¿Cómo elijo productos para mi tipo de piel?",
    qa_a2: "Cada página de producto muestra el tipo de piel recomendado.",
    qa_q3: "¿Hacen pruebas en animales?",
    qa_a3: "Absolutamente no. Bloom & Grace es cruelty-free.",
    qa_q4: "¿Cuánto tarda el envío?",
    qa_a4: "El envío doméstico llega en 2-3 días hábiles.",
    qa_q5: "¿Cuáles son los costos de envío?",
    qa_a5: "Envío gratis en pedidos mayores a $50.",
    qa_q6: "¿Puedo cancelar o modificar mi pedido?",
    qa_a6: "Sí, hasta la etapa de preparación del envío.",
    qa_q7: "¿Cómo devuelvo un producto?",
    qa_a7: "Devoluciones disponibles dentro de 7 días para productos sin abrir.",
    qa_q8: "Recibí un producto defectuoso.",
    qa_a8: "Ofrecemos reembolso o cambio completo para productos defectuosos.",
    qa_q9: "¿Hay beneficios por registrarse?",
    qa_a9: "Nuevos miembros reciben cupón de 10% de descuento.",
    qa_q10: "¿Cómo uso los puntos de recompensa?",
    qa_a10: "Los puntos se pueden usar desde $1 como efectivo.",
    qa_q11: "¿Usan empaque ecológico?",
    qa_a11: "Sí, todos los productos usan materiales reciclables.",
    qa_q12: "¿Ofrecen recargas?",
    qa_a12: "Sí, las líneas principales ofrecen recargas con 20% de descuento.",
    qa_q13: "¿Cuál es el horario de atención?",
    qa_a13: "Lunes a viernes de 10 AM a 6 PM.",
    qa_q14: "¿Hay consulta personalizada?",
    qa_a14: "Sí, por chat o email a contact@bloomandgrace.com.",

    currency: "$",
    currency_suffix: "",
  },
  de: {
    nav_home: "Startseite",
    nav_products: "Produkte",
    nav_all_products: "Alle Produkte",
    nav_skincare: "Hautpflege",
    nav_skincare_desc: "Hautpflegeprodukte",
    nav_makeup: "Make-up",
    nav_makeup_desc: "Farbkosmetik",
    nav_haircare: "Haarpflege",
    nav_haircare_desc: "Haarpflege",
    nav_fragrance: "Düfte",
    nav_fragrance_desc: "Exklusive Parfums",
    nav_bodycare: "Körperpflege",
    nav_bodycare_desc: "Körperpflegeprodukte",
    nav_health: "Nahrungsergänzung",
    nav_health_desc: "Nahrungsergänzungsmittel",
    nav_brand_story: "Unsere Geschichte",
    nav_qa: "FAQ",
    nav_contact: "Kontakt",
    nav_admin: "Admin",
    nav_menu: "Menü",
    nav_mypage: "Mein Konto",
    nav_login: "Anmelden",

    hero_tagline: "Premium Koreanische Schönheit",
    hero_title: "Bloom & Grace",
    hero_subtitle: "Premium-Kosmetik mit der Weisheit koreanischer Schönheit. Mit den besten natürlichen Zutaten für Ihre Eleganz.",
    hero_shop: "Kollektion ansehen",
    hero_story: "Unsere Geschichte",

    featured_tagline: "Exklusive Kollektion",
    featured_title: "Empfohlene Produkte",
    featured_subtitle: "Premium-Beauty-Essentials mit koreanischer Schönheit",
    featured_view_all: "Alle Produkte",

    about_tagline: "Unsere Philosophie",
    about_title: "Unsere Geschichte",
    about_p1: "Willkommen bei Bloom & Grace, wo koreanische Schönheitsweisheit auf die sanfte Umarmung des Herbstes trifft. Unsere Boutique ist ein Refugium raffinierter Eleganz.",
    about_p2: "Jedes Produkt verkörpert die sorgfältige Pflege koreanischer Schönheitstraditionen—durchdrungen von natürlichen Pflanzenextrakten und den besten Zutaten der Natur.",
    about_p3: "Von unseren exklusiven Formulierungen bis zu unserem durchdacht gestalteten Verpackungsdesign ist jedes Element darauf ausgerichtet, Ihre natürliche Ausstrahlung zu verstärken.",
    about_since: "Mit Sorgfalt gefertigt seit 2024",

    footer_desc: "Premium-Kosmetikmarke mit koreanischer Schönheitsweisheit.",
    footer_products: "Produkte",
    footer_new: "Neuheiten",
    footer_bestseller: "Bestseller",
    footer_brand: "Marke",
    footer_store: "Filialen",
    footer_sustainability: "Nachhaltigkeit",
    footer_ingredients: "Inhaltsstoffe",
    footer_careers: "Karriere",
    footer_support: "Support",
    footer_faq: "Häufige Fragen",
    footer_shipping: "Versand",
    footer_returns: "Rückgabe",
    footer_terms: "AGB",
    footer_rights: "Alle Rechte vorbehalten.",
    footer_cs: "Kundenservice: 1588-1234 | E-Mail: contact@bloomandgrace.com",

    products_title: "Alle Produkte",
    products_subtitle: "Premium koreanische Kosmetik-Kollektion",
    products_search: "Produkte suchen...",
    products_search_btn: "Suchen",
    products_all: "Alle",
    products_category: "Kategorie",
    products_popular: "Beliebt",
    products_newest: "Neueste",
    products_price_low: "Preis aufsteigend",
    products_price_high: "Preis absteigend",
    products_rating: "Bestbewertet",
    products_all_prices: "Alle Preise",
    products_under_20k: "Unter 20€",
    products_20k_50k: "20€ - 50€",
    products_over_50k: "Über 50€",
    products_no_results: "Keine Produkte gefunden.",

    pd_reviews: "Bewertungen",
    pd_stock: "Auf Lager",
    pd_out_of_stock: "Ausverkauft",
    pd_add_to_cart: "In den Warenkorb",
    pd_review_section: "Bewertungen",
    pd_all: "Alle",
    pd_above: "und mehr",
    pd_write_review: "Bewertung schreiben",
    pd_review_title: "Titel",
    pd_review_content: "Schreiben Sie Ihre Bewertung...",
    pd_submit_review: "Absenden",
    pd_no_reviews: "Noch keine Bewertungen.",
    pd_anonymous: "Anonym",
    pd_loading: "Laden...",
    pd_not_found: "Produkt nicht gefunden.",
    pd_already_reviewed: "Sie haben bereits bewertet.",
    pd_review_fail: "Bewertung fehlgeschlagen.",
    pd_review_success: "Bewertung eingereicht!",

    cart_title: "Warenkorb",
    cart_empty: "Ihr Warenkorb ist leer",
    cart_total: "Gesamt",
    cart_checkout: "Zur Kasse",
    cart_added: "Zum Warenkorb hinzugefügt!",
    cart_login_required: "Bitte melden Sie sich an.",

    pc_add_to_cart: "In den Korb",

    auth_title: "Bloom & Grace",
    auth_subtitle: "Premium Koreanische Kosmetik",
    auth_login: "Anmelden",
    auth_signup: "Mitglied werden",
    auth_email: "E-Mail",
    auth_email_placeholder: "Ihre E-Mail",
    auth_password: "Passwort",
    auth_password_placeholder: "Ihr Passwort",
    auth_name: "Name",
    auth_name_placeholder: "Ihr Name",
    auth_phone: "Telefon",
    auth_phone_placeholder: "Ihre Telefonnummer",
    auth_confirm_password: "Passwort bestätigen",
    auth_confirm_password_placeholder: "Passwort wiederholen",
    auth_logging_in: "Anmelden...",
    auth_signing_up: "Registrieren...",
    auth_login_success: "Angemeldet!",
    auth_login_fail: "Anmeldung fehlgeschlagen.",
    auth_signup_success: "Konto erstellt! Bitte Profil vervollständigen.",
    auth_signup_fail: "Registrierung fehlgeschlagen.",
    auth_google_signin: "Mit Google anmelden",
    auth_google_signup: "Mit Google registrieren",
    auth_or: "oder",
    auth_password_mismatch: "Passwörter stimmen nicht überein.",
    auth_agree_required: "Bitte stimmen Sie den Bedingungen zu.",
    auth_terms_agree: "Ich stimme den AGB und der Datenschutzerklärung zu.",
    auth_benefits_title: "Mitgliedsvorteile",
    auth_benefit_1: "10% Willkommensgutschein bei Registrierung",
    auth_benefit_2: "3% Bonuspunkte auf jeden Einkauf",
    auth_benefit_3: "Spezielle Geschenke im Geburtstagsmonat",
    cp_title: "Profil vervollständigen",
    cp_subtitle: "Bitte geben Sie Ihre Lieferadresse ein, um mit dem Einkaufen zu beginnen.",
    cp_country: "Land",
    cp_country_code: "Ländercode",
    cp_address: "Adresse",
    cp_detail_address: "Adresszusatz",
    cp_shipping_address: "Lieferadresse",
    cp_customs_number: "Zollnummer",
    cp_customs_hint: "Erforderlich für internationalen Versand",
    cp_postal: "PLZ",
    cp_city: "Stadt / Bundesland",
    cp_phone: "Telefon",
    cp_save: "Speichern & Weiter",
    cp_saving: "Speichern...",
    cp_skip: "Später ausfüllen",
    cp_success: "Profil gespeichert!",
    cp_fail: "Fehler beim Speichern.",

    co_shipping: "Lieferadresse",
    co_recipient: "Empfänger",
    co_phone: "Telefon",
    co_address: "Adresse",
    co_detail_address: "Adresszusatz",
    co_postal: "PLZ",
    co_city: "Stadt",
    co_payment: "Zahlungsmethode",
    co_card: "Kreditkarte",
    co_bank: "Überweisung",
    co_kakao: "KakaoPay",
    co_naver: "NaverPay",
    co_summary: "Bestellübersicht",
    co_coupon: "Gutscheincode",
    co_apply: "Anwenden",
    co_discount: "Rabatt",
    co_total: "Gesamt",
    co_processing: "Verarbeitung...",
    co_pay: "Bezahlen",
    co_login_required: "Bitte melden Sie sich an.",
    co_cart_empty: "Ihr Warenkorb ist leer.",
    co_invalid_coupon: "Ungültiger Gutschein.",
    co_min_order: "Mindestbestellwert ist",
    co_coupon_applied: "Gutschein angewendet!",
    co_discount_amount: "Rabatt",
    co_order_success: "Bestellung aufgegeben!",
    co_order_fail: "Bestellung fehlgeschlagen.",

    mp_title: "Mein Konto",
    mp_logout: "Abmelden",
    mp_orders: "Bestellungen",
    mp_wishlist: "Wunschliste",
    mp_profile: "Profil",
    mp_no_orders: "Keine Bestellungen.",
    mp_order_date: "Bestellung",
    mp_subtotal: "Zwischensumme",
    mp_no_wishlist: "Wunschliste leer.",
    mp_email: "E-Mail",
    mp_name: "Name",
    mp_phone: "Telefon",
    mp_login_required: "Bitte melden Sie sich an.",

    status_pending: "Ausstehend",
    status_confirmed: "Bestätigt",
    status_shipping: "Im Versand",
    status_delivered: "Zugestellt",
    status_cancelled: "Storniert",

    contact_tagline: "Kontakt",
    contact_title: "Kontaktieren Sie uns",
    contact_subtitle: "Haben Sie Fragen? Wir sind für Sie da.",
    contact_send: "Nachricht senden",
    contact_name: "Name",
    contact_email: "E-Mail",
    contact_phone: "Telefon",
    contact_message: "Nachricht",
    contact_message_placeholder: "Was möchten Sie uns mitteilen...",
    contact_submit: "Senden",
    contact_info: "Kontaktinformationen",
    contact_address_title: "Hauptsitz",
    contact_address_value: "123 Teheranro, Gangnam-gu\nSeoul, Südkorea",
    contact_phone_title: "Telefon",
    contact_phone_value: "Zentrale: +82-2-1234-5678\nSupport: 1588-1234",
    contact_email_title: "E-Mail",
    contact_email_value: "Allgemein: contact@bloomandgrace.com\nPartner: partnership@bloomandgrace.com",
    contact_hours_title: "Öffnungszeiten",
    contact_hours_value: "Mo-Fr: 10:00 - 18:00\nMittagspause: 12:00 - 13:00\nWochenende: Geschlossen",
    contact_visit: "Besuch buchen",
    contact_visit_desc: "Reservieren Sie vorab für eine bequemere Beratung.",
    contact_reserve: "Reservieren",
    contact_map: "Anfahrt",
    contact_map_desc: "Kartenbereich",

    qa_tagline: "Häufige Fragen",
    qa_title: "Fragen & Antworten",
    qa_subtitle: "Wir haben die häufigsten Fragen zusammengestellt. Kontaktieren Sie uns gerne.",
    qa_not_found: "Keine Antwort gefunden?",
    qa_not_found_desc: "Kontaktieren Sie uns und wir helfen gerne.",
    qa_email_btn: "E-Mail senden",
    qa_phone_btn: "Anrufen",
    qa_cat_product: "Produkte",
    qa_cat_shipping: "Versand & Bestellungen",
    qa_cat_returns: "Rückgabe & Umtausch",
    qa_cat_membership: "Mitgliedschaft",
    qa_cat_sustainability: "Nachhaltigkeit",
    qa_cat_support: "Kundenservice",
    qa_q1: "Aus welchen Inhaltsstoffen bestehen Ihre Produkte?",
    qa_a1: "Unsere Produkte werden mit premium koreanischen Naturzutaten hergestellt.",
    qa_q2: "Wie wähle ich Produkte für meinen Hauttyp?",
    qa_a2: "Jede Produktseite zeigt den empfohlenen Hauttyp an.",
    qa_q3: "Testen Sie an Tieren?",
    qa_a3: "Nein. Bloom & Grace ist cruelty-free zertifiziert.",
    qa_q4: "Wie lange dauert der Versand?",
    qa_a4: "Inlandsversand dauert 2-3 Werktage.",
    qa_q5: "Was kostet der Versand?",
    qa_a5: "Kostenloser Versand ab 50€ Bestellwert.",
    qa_q6: "Kann ich meine Bestellung stornieren?",
    qa_a6: "Ja, bis zur Versandvorbereitung.",
    qa_q7: "Wie gebe ich ein Produkt zurück?",
    qa_a7: "Rückgabe innerhalb von 7 Tagen für ungeöffnete Produkte.",
    qa_q8: "Ich habe ein defektes Produkt erhalten.",
    qa_a8: "Volle Rückerstattung oder Umtausch für defekte Produkte.",
    qa_q9: "Gibt es Vorteile bei der Registrierung?",
    qa_a9: "Neue Mitglieder erhalten einen 10% Rabattgutschein.",
    qa_q10: "Wie nutze ich Bonuspunkte?",
    qa_a10: "Punkte können ab 1€ wie Bargeld eingesetzt werden.",
    qa_q11: "Verwenden Sie umweltfreundliche Verpackungen?",
    qa_a11: "Ja, alle Produkte werden mit recycelbaren Materialien verpackt.",
    qa_q12: "Gibt es Nachfüllprodukte?",
    qa_a12: "Ja, Hauptpflegelinien bieten Nachfüllungen mit 20% Rabatt.",
    qa_q13: "Wann ist der Kundenservice erreichbar?",
    qa_a13: "Montag bis Freitag von 10 bis 18 Uhr.",
    qa_q14: "Gibt es persönliche Beratung?",
    qa_a14: "Ja, per Chat oder E-Mail an contact@bloomandgrace.com.",

    currency: "€",
    currency_suffix: "",
  },
};

type TranslationKey = keyof typeof translations.en;

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: TranslationKey) => string;
  formatPrice: (price: number) => string;
}

const LanguageContext = createContext<LanguageContextType>({} as LanguageContextType);

export const useLanguage = () => useContext(LanguageContext);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem("bloom-lang");
    return (saved as Language) || "en";
  });

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem("bloom-lang", lang);
  };

  const t = (key: TranslationKey): string => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  const formatPrice = (price: number): string => {
    const curr = translations[language];
    if (language === "ko") {
      return `${price.toLocaleString()}${curr.currency_suffix}`;
    }
    // Convert KRW to approximate USD/EUR for display
    const converted = language === "de" ? (price / 1400).toFixed(2) : (price / 1300).toFixed(2);
    return `${curr.currency}${converted}${curr.currency_suffix}`;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t, formatPrice }}>
      {children}
    </LanguageContext.Provider>
  );
};
